- name: Update kernel parameters
  register: k3s_cluster_kernel_parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - name: vm.panic_on_oom
      value: 0
    - name: vm.overcommit_memory
      value: 1
    - name: kernel.panic
      value: 10
    - name: kernel.panic_on_oops
      value: 1

- name: Reboot machine  # noqa no-handler (Must happen immediately)
  when: k3s_cluster_kernel_parameters.changed
  throttle: 1
  ansible.builtin.reboot:

- name: Create kubelet.conf
  notify: Apply kubelet.conf
  ansible.builtin.copy:
    dest: /etc/sysctl.d/90-kubelet.conf
    owner: root
    group: root
    mode: 0640
    content: "{{ lookup('template', 'kubelet.conf.j2') }}"
    force: true

- name: Create audit log directory
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/logs
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Create audit policy
  ansible.builtin.copy:
    dest: /var/lib/rancher/k3s/server/audit.yaml
    owner: root
    group: root
    mode: 0644
    content: "{{ lookup('template', 'audit.yml.j2') }}"
    force: true
