- name: Install required pip modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: kubernetes
      - name: kubernetes-validate
