- name: Configure custom hosts
  notify: restart_dns
  ansible.builtin.copy:
    dest: /etc/pihole/custom.list
    owner: pihole
    group: pihole
    mode: 0644
    content: "{{ lookup('template', 'custom-hosts.j2') }}"

- name: Configure local domain
  notify: restart_dns
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/local-domain.conf
    owner: pihole
    group: pihole
    mode: 0644
    content: "{{ lookup('template', 'dnsmasq-local.j2') }}"

- name: Configure explicit domain specific forwarders
  notify: restart_dns
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/custom-forwarders.conf
    owner: pihole
    group: pihole
    mode: 0644
    content: "{{ lookup('template', 'dnsmasq-forwarders.j2') }}"