- name: Download pihole
  ansible.builtin.get_url:
    url: https://github.com/pi-hole/pi-hole/archive/refs/tags/v{{ app_pihole_version }}.zip
    dest: /tmp/pihole.zip

- name: Extract pihole
  ansible.builtin.unarchive:
    src: /tmp/pihole.zip
    dest: /tmp
    remote_src: yes

- name: Install pihole
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      cat '/tmp/pi-hole-{{ app_pihole_version }}/automated install/basic-install.sh' | bash /dev/stdin --unattended