- name: Create configuration directory
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: 0750

- name: Create setupvars
  ansible.builtin.copy:
    dest: /etc/pihole/setupVars.conf
    owner: pihole
    group: pihole
    mode: 0640
    force: true
    content: "{{ lookup('template', 'setup-vars.j2') }}"

- name: Check if pihole already installed
  register: app_pihole_bin
  ansible.builtin.stat:
    path: /usr/local/bin/pihole
    
- name: Install pihole
  when: not app_pihole_bin.stat.exists
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Configure DNS
  ansible.builtin.include_tasks:
    file: dns.yaml