- name: Create cron for automated certificate renewal
  ansible.builtin.cron:
    name: "getssl-renewal"
    cron_file: getssl-renewal
    user: root
    job: "/usr/bin/getssl -u -a -w /etc/pve/getssl &>> /var/log/getssl.log"
    hour: "{{ getssl_cron_renewal_hour | default(17) }}"
    minute: 0

- name: Create cron for automated certificate push to the containers
  ansible.builtin.cron:
    name: "getssl-containers"
    cron_file: getssl-containers
    user: root
    job: "/usr/bin/getssl-copy-container-all &>> /var/log/getssl-containers.log"
    hour: 20
    minute: 0

- name: Create cron to update pve proxy certificate
  ansible.builtin.cron:
    name: "getssl-pveproxy"
    cron_file: getssl-pveproxy
    user: root
    job: "/usr/bin/getssl-copy-pveproxy \"{{ (getssl_certificates | selectattr('pveproxy', 'defined') | selectattr('pveproxy', 'equalto', true) | first).domain }}\" &>> /var/log/getssl-pveproxy.log"
    hour: 23
    minute: 0