app_frigate_cameras:
    - name: ENC[AES256_GCM,data:K25rEW2YZ9k=,iv:3F+cPXgvnpqDX3Jul8Bd+CpgUVK4EBk6SSqK/7nsiTk=,tag:MjTIJKnJNRrm9r1C5DAILw==,type:str]
      type: ENC[AES256_GCM,data:VWA/UV1mWA==,iv:wnOsUQPwYyluSKd+pgzBXrNlFNYdsUuV7iMOEg3zLCY=,tag:Bf90sQ0Xi/6GY6gGnAm2Sw==,type:str]
      ip: ENC[AES256_GCM,data:bcgx95kQUEEF,iv:URoVES75H5OaTjoPnwrTacxvoS0pWrIdDopMDo1qRpk=,tag:yS/IoVOFbunyXFxET3lubQ==,type:str]
      username: ENC[AES256_GCM,data:Jb/lH4qKqw==,iv:N6rrdzEnaS6IkvyuH/GVsNsutzkrx1wZ2kWnVo37NE4=,tag:kbWDUwIZNcSPzJsTv9E7ZQ==,type:str]
      password: ENC[AES256_GCM,data:IvToLCZj1wq5KH2MQaaTu7dCQcSWW8LdxLnykcs=,iv:yB03KVTEtB5PwXvv4zfj/zMQLKIr76fNjjv3rcyc2bA=,tag:CKw79/Hye5imT3v4Blp0sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zw6c356patclh7q8cq5a99cghpzmnufgtwfaa0tmcg87a038d9ms4xpytn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWWFad3hDUi8vWFpIQ3E1
            QktDNVVtdXluVlQ1UzJjQ1BZWFRXUlpUc1NjClV2WEd0bFRhK2JlcDBwOUVUWmNo
            RHBFbWFsY1lRYWtaRE5ScXBrZ0UzanMKLS0tIDByNmd0K3drUUpGU3hmcmJUQmpu
            L0w0ZXlhN2hPS0xWR0lITW96Mm5kMU0KgOqDc2YVPVQtP2+5lfjUXyFLMj0idIEn
            NnVcBcGCpRaU2NOh2vTSIJTPDF8oq1wCR1MCxycKV4U9Za5caPurbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T15:14:03Z"
    mac: ENC[AES256_GCM,data:vqkakCWFV2k9zct5w2vDpvJTsdsrU86TVTplcrMOZm3e9dPMDARpHXZI4vYBTBPtU7JNhDNFgQNPUB/D/A+Ig5BGvL3C1iPmKTvmGjv/w4NaEn8yRj4k0+2h5XSZNEaIQoq65Ymzbbkz714kuTRn2ctrQxfJCbj8Tas9aoDbM/0=,iv:FaTwuWFR7FPpNMuufSUsiL5AhgMWc+9KLr3tfRMpyK0=,tag:GT/yiuF5LY1RS2uql2OIlA==,type:str]
    pgp:
        - created_at: "2024-03-14T15:10:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7Pg+ndCcR5CAQ//chnODy6vHHlkjG7FCrZIk3sL6OgnSjadjNhoxTvuYEuK
            WNIiS1zMw3aVVrqVYq1+SXeUgwPTB63GP1fzNrLYY9B4g1zvxq4ySjQ1l5AFtKse
            PmOcPWQrkSzahquMFsNDiJlwEIlVmoAm1V14uI85TehIBmXjlBIJcckvikkf2xBi
            /7FGoLqXdnrpCdeEYWIiujujJF1saIuhBWLEcPyzzL7fgtlrOQH+IcTkqLvEP92k
            p0FA4152ohwP2duAsH4By3AR5iWTywP19tKzp7E/cu16g0cbqbD/L7kpoMB1wkmI
            6nXJ5SHrSZ1RD7PppX/PQbeTOaYRbW6jnqLvI/2AOx8ChNO6DdXJr4qi/TuTyAQR
            RSapnAyYVyfxffQdozT0vjJPrHR7AQSlz6q3/3O0b4VL3SkUDH8eoLjaIIAt0oz5
            57Fjrrr9gtRdLZM+DrxFqmUk+q0PFEmriYY0gqBjDeTMS/gWJ7r4DoBgsH5QeN4p
            zti3fEEysaVUVs5GaDKeV2yXgT3j3DqVdiLGoO7YeLiO4uAU4Z2gOPZs+vy7Xptb
            UVGgQqm6BQe9pkEq94zbGqSe9+6+16pZ/PGeGZ+riE8XvioJ2r+O9M/zaSO8dSn6
            IKkxeWDcvDD4LL6KJyqT8uWtYncKEorMp6TRa7ZGaj6gbPQXhhPKUVqt79Yj1lfS
            XgFpmG+dMte5yG5aX5WyFzfk9GqVJck2LU3HoQyOb7KqA5KblSZc54jESc1mkH2d
            tALRYJzfO18P9RNv9HWtVKBgr4GZ42XR13r3rOJAF9mypPkOp9bCoCvT8kAGmF0=
            =ltPj
            -----END PGP MESSAGE-----
          fp: 2D1D9C803F35BBC24014C3906601E1EB2454827F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
