# ??? app_container_memory: 2048
app_container_storage_name: dpool1
app_container_storage_size_gb: 5

app_container_mounts:
  - type: disk
    storage_name: dpool
    index: 2
    size_gb: 2
    target_path: /nvr

app_frigate_image_tag: 0.13.2
