# Common
ansible_host: 10.1.2.22
ansible_hostname: kube2
fqdn: kube2.homecentr.one

# Gluster
gluster_mount_host: pve2

# Kubernetes
k3s_cluster_join: https://kube1:6443

k3s_cluster_node_labels:
  - name: homecentr.one/tpu
    value: "true"

# nVidia drivers
nvidia_drivers_install_containers: true