# Common
ansible_host: 10.1.2.11
ansible_hostname: pve1
fqdn: pve1.homecentr.one

# UPS
ups_name: ups1

# Gluster
gluster_ip: 10.1.7.11
gluster_hostname: gfs-pve1
gluster_fqdn: gfs-pve1.homecentr.one
gluster_mount_host: pve1

# PVE
pve_vm_machines:
  - vmid: 101
    name: kube1
    protection: false
    cloud_image_filename: debian-11.5.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size_gb: 128
    cpu_count: 2
    cpu_cores_per_cpu: 9
    min_memory: 16384
    max_memory: 98304
    nic_ipv4_address: 10.1.2.21
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.2.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

# ClamAV
# clamav_scanned_dirs:
#   - /user-data0
#   - /user-data1
