# Common
ansible_host: 10.1.2.12
ansible_hostname: pve2
fqdn: pve2.homecentr.one

# UPS
ups_name: ups2

# Gluster
gluster_ip: 10.1.7.12
gluster_hostname: gfs-pve2
gluster_fqdn: gfs-pve2.homecentr.one
gluster_mount_host: pve2

# PVE
pve_pci_passhthrough_enabled: true

pve_vm_machines:
  - vmid: 201
    name: kube2
    protection: false
    cloud_image_filename: debian-11.5.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size_gb: 128
    cpu_type: "cputype=host,flags=+aes"
    cpu_count: 2
    cpu_cores_per_cpu: 13
    min_memory: 16384
    max_memory: 98304
    nic_ipv4_address: 10.1.2.22
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.2.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

# ClamAV
# clamav_scanned_dirs:
#   - /user-data0
#   - /user-data1
