# Common
ansible_host: 10.1.2.13
ansible_hostname: pve3
fqdn: pve3.homecentr.one

# UPS
ups_name: ups1

# PVE
pve_vm_machines:
  - vmid: 301
    name: kube3
    protection: false
    cloud_image_filename: debian-12.1.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size: 32G
    cpu_type: "cputype=host,flags=+aes"
    cpu_count: 1
    cpu_cores_per_cpu: 3
    min_memory: 8192
    max_memory: 8192
    nic_ipv4_address: 10.1.2.23
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.2.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

# ClamAV
# clamav_scanned_dirs:
#   - /usr/local/gfs
