# Common
ansible_host: 10.1.2.26
fqdn: pve3.homecentr.one

# UPS
ups_name: ups1

# Gluster
gluster_ip: 10.1.7.26
gluster_hostname: gfs-pve3
gluster_fqdn: gfs-pve3.homecentr.one
gluster_mount_host: pve3

# PVE
pve_vm_machines:
  - vmid: 301
    name: kube3
    protection: false
    cloud_image_filename: debian-11.5.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size_gb: 32
    cpu_count: 1
    cpu_cores_per_cpu: 3
    min_memory: 4096
    max_memory: 4096
    nic_ipv4_address: 10.1.2.50
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.2.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
