fleet_version: 0.5.0
fleet_cluster_environment: lab

fleet_git_repository:
  name: homecentr
  url: https://github.com/homecentr/fleet
  polling_interval: 10s
  branch: lab
  paths:
    - /infra/*
    - /apps/*
