- name: Configure Cloudflare issuer
  run_once: true
  k8s:
    kubeconfig: "{{ certmanager_kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    apply: yes
    state: present
  with_items:
    - "cloudflare-secret.yml.j2"
    - "cloudflare-issuer.yml.j2"