- name: Add jetstack helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
    state: present

- name: Deploy cert-manager
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    chart_version: "{{ certmanager_chart_version }}"
    chart_ref: jetstack/cert-manager
    kubeconfig_path: "{{ certmanager_kubeconfig_path }}"
    values:
      installCRDs: true
      webhook:
        securePort: "{{ certmanager_webhook_secure_port }}"
        # podAnnotations:
        #   container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
        #   seccomp.security.alpha.kubernetes.io/pod: runtime/default
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            memory: 128Mi
        containerSecurityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          readOnlyRootFilesystem: true
          capabilities:
              drop:
              - all
      cainjector:
        # podAnnotations:
        #   container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
        #   seccomp.security.alpha.kubernetes.io/pod: runtime/default
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            memory: 128Mi
        containerSecurityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          readOnlyRootFilesystem: true
          capabilities:
              drop:
              - all
      # podAnnotations:
      #   container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
      #   seccomp.security.alpha.kubernetes.io/pod: runtime/default
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          memory: 128Mi
      containerSecurityContext:
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        readOnlyRootFilesystem: true
        capabilities:
            drop:
            - all