- name: Create resources
  run_once: true
  debug:
    msg: "{{ lookup('template', item) }}"
  with_items:
    - "network-policy-allow-kubeapi.yml.j2"

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ certmanager_kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    apply: yes
    state: present
  with_items:
    - "network-policy-allow-internal.yml.j2"
    - "network-policy-allow-kubeapi.yml.j2"
    - "network-policy-allow-dns.yml.j2"
    - "network-policy-allow-http.yml.j2"
    # - "network-policy-allow-metrics.yml.j2" TBA - when prometheus is set up
    - "network-policy-allow-webhook.yml.j2"