---
all:
  children:
    pve_nodes:
      hosts:
        stg-pve1:
        stg-pve2:
    # k8s_nodes:
    #   hosts:
    #     stg-kube1:
    #     stg-kube2:
    ups_masters:
      hosts:
        stg-pve1:
    ups_slaves:
      hosts:
        stg-pve2:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            stg-pve1:
            stg-pve2:
        gluster_clients:
          hosts:
            stg-pve1:
            stg-pve2:
            # stg-kube1:
            # stg-kube2: