apiVersion: v1
kind: Secret
metadata:
  name: calico-apiserver-certs
  namespace: calico-apiserver
data:
  apiserver.key: "{{ k8s_cluster_calico_apiserver_private_key | b64encode }}"
  apiserver.crt: "{{ k8s_cluster_calico_apiserver_public_key | b64encode }}"
