---
collections:
  - name: oasis_roles.system
  - name: community.general
    version: 4.5.0
  - name: gluster.gluster
    version: 1.0.2
  - name: kubernetes.core
    version: 2.3.2
  - name: community.crypto
    version: 2.5.0

roles:
  - name: geerlingguy.docker
    version: 3.0.0
  - name: geerlingguy.pip
  - name: geerlingguy.security
  - name: geerlingguy.clamav
  - name: geerlingguy.helm
  - name: cloudalchemy.node_exporter
    version: 2.0.0
