pve_cluster_firewall_enabled: false

pve_cluster_firewall_aliases:
  - name: subnet-home
    cidr: 10.1.3.0/24
  - name: subnet-services
    cidr: "{{ subnets.services }}"

  - name: "pve1{{ env.suffix }}"
    cidr: "{{ subnets.services | ansible.utils.ipmath(11) }}/32"
  - name: "pve2{{ env.suffix }}"
    cidr: "{{ subnets.services | ansible.utils.ipmath(12) }}/32"
  - name: "pve3{{ env.suffix }}"
    cidr: "{{ subnets.services | ansible.utils.ipmath(13) }}/32"

  - name: "cloudflared1{{ env.suffix }}"
    cidr: "{{ subnets.services | ansible.utils.ipmath(70) }}/32"
  - name: "cloudflared2{{ env.suffix }}"
    cidr: "{{ subnets.services | ansible.utils.ipmath(71) }}/32"

  - name: mqtt
    cidr: 10.1.8.67/32

  - name: homepage
    cidr: 10.1.8.72/32

  - name: pomerium1
    cidr: 10.1.8.66/32


pve_cluster_firewall_ipsets:
  - name: management
    items:
      - type: alias
        name: subnet-home
      - type: alias
        name: monitoring
  - name: proxmox
    items:
      - type: alias
        name: pve1
      - type: alias
        name: pve2
      - type: alias
        name: pve3
  - name: pomerium
    items:
      - type: alias
        name: pomerium1
  - name: mqtt
    items:
      - type: alias
        name: mqtt
  - name: monitoring
    items:
      - type: alias
        name: monitoring
  - name: homepage
    items:
      - type: alias
        name: homepage

pve_cluster_firewall_security_groups: []
