pve_cluster_firewall_enabled: false

pve_cluster_firewall_aliases:
  - name: subnet-home
    cidr: 10.1.3.0/24
  - name: subnet-services
    cidr: "{{ subnets.services }}"

  - name: "pve1{{ env.suffix }}"
    cidr: "{{ ipam.pve1 }}/32"
  - name: "pve2{{ env.suffix }}"
    cidr: "{{ ipam.pve2 }}/32"
  - name: "pve3{{ env.suffix }}"
    cidr: "{{ ipam.pve3 }}/32"

  - name: "ct-pihole{{ env.suffix }}"
    cidr: "{{ ipam.pihole }}/32"
  - name: "ct-smtp-relay{{ env.suffix }}"
    cidr: "{{ ipam.smtp_relay }}/32"
  - name: "ct-pomerium{{ env.suffix }}"
    cidr: "{{ ipam.pomerium }}/32"
  - name: "ct-mqtt{{ env.suffix }}"
    cidr: "{{ ipam.mqtt }}/32"
  - name: "ct-monitoring{{ env.suffix }}"
    cidr: "{{ ipam.monitoring }}/32"
  - name: "ct-frigate{{ env.suffix }}"
    cidr: "{{ ipam.frigate }}/32"
  - name: "ct-cloudflared1{{ env.suffix }}"
    cidr: "{{ ipam.cloudflared }}/32"
  - name: "ct-cloudflared2{{ env.suffix }}"
    cidr: "{{ ipam.cloudflared }}/32"
  - name: "ct-homepage{{ env.suffix }}"
    cidr: "{{ ipam.homepage }}/32"
  - name: ct-unifi-controller{{ env.suffix }}"
    cidr: "{{ ipam.unifi_controller }}/32"

pve_cluster_firewall_ipsets:
  - name: management
    items:
      - type: alias
        name: subnet-home
      - type: alias
        name: monitoring
  - name: proxmox
    items:
      - type: alias
        name: "pve1{{ env.suffix }}"
      - type: alias
        name: "pve1{{ env.suffix }}"
      - type: alias
        name: "pve1{{ env.suffix }}"
  - name: cloudflared
    items:
      - type: alias
        name: "ct-cloudflared1{{ env.suffix }}"
      - type: alias
        name: "ct-cloudflared2{{ env.suffix }}"

pve_cluster_firewall_security_groups: []
