- name: Install Traefik
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: ingress
    release_namespace: kube-system
    create_namespace: no
    chart_version: "{{ ingress_traefik_chart_version }}"
    chart_ref: traefik
    chart_repo_url: https://traefik.github.io/charts
    kubeconfig_path: "{{ ingress_kubeconfig_path }}"
    wait: true
    values:
      dashboard:
        enable: true
        ingressRoute: true
      nameOverride: ingress
      priorityClassName: system-cluster-critical
      service:
        annotations:
          metallb.universe.tf/allow-shared-ip: "ingress"
          metallb.universe.tf/loadBalancerIPs: "{{ ingress_ipv4_address }}"

# TODO: Create network policy !!!!