- name: Configure apt repositories
  ansible.builtin.include_tasks:
    file: apt.yml

- name: Expose Web UI on port 443
  ansible.builtin.include_tasks:
    file: port-forwarding.yml

- name: Configure SMTP for alerts
  ansible.builtin.include_tasks:
    file: smtp.yml

- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Improve PVE Cluster auto-heal
  ansible.builtin.include_tasks:
    file: cluster.yml
