- name: Configure network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Configure apt repositories
  ansible.builtin.include_tasks:
    file: apt-repositories.yml

- name: Upgrade
  ansible.builtin.include_tasks:
    file: apt-upgrade.yml

- name: Expose Web UI on port 443
  ansible.builtin.include_tasks:
    file: port-forwarding.yml

- name: Configure SMTP for alerts
  ansible.builtin.include_tasks:
    file: smtp.yml

- name: Configure ZFS
  ansible.builtin.include_tasks:
    file: zfs.yml

- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Configure SSO via OpenID
  ansible.builtin.include_tasks:
    file: sso-openid.yml

- name: Configure SSO users
  ansible.builtin.include_tasks:
    file: users.yml

- name: Improve PVE Cluster auto-heal
  ansible.builtin.include_tasks:
    file: cluster.yml
