- name: Configure nameservers
  ansible.builtin.include_tasks:
    file: network-dns.yml

- name: Configure network interfaces
  ansible.builtin.include_tasks:
    file: network-interface.yml
  loop: "{{ pve_network_interfaces | dict2items }}"
  loop_control:
    loop_var: interface
  when: pve_network_interfaces is defined
  vars:
    interface_name: "{{ interface.key }}"

- name: Configure apt repositories
  ansible.builtin.include_tasks:
    file: apt-repositories.yml

- name: Install required python modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - passlib # Required for users' password hash computation

- name: Upgrade
  ansible.builtin.include_tasks:
    file: apt-upgrade.yml

- name: Expose Web UI on port 443
  ansible.builtin.include_tasks:
    file: port-forwarding.yml

- name: Configure SMTP for alerts
  ansible.builtin.include_tasks:
    file: smtp.yml

- name: Configure ZFS
  ansible.builtin.include_tasks:
    file: zfs.yml

- name: Configure USB HID
  ansible.builtin.include_tasks:
    file: usbhid.yml

- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Configure SSO via OpenID
  ansible.builtin.include_tasks:
    file: sso-openid.yml

- name: Configure SSO users
  ansible.builtin.include_tasks:
    file: users.yml

- name: Improve PVE Cluster auto-heal
  ansible.builtin.include_tasks:
    file: cluster.yml

- name: Enable PCI passthrough
  ansible.builtin.include_tasks:
    file: pci-passthrough.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers # restart networking immediately if needed
