# DNS - render template
# Interfaces - Loopback, vmbr should remain intact (?)
- name: Configure nameservers
  ansible.builtin.copy:
    content: "{{ lookup('template', 'resolv.conf.j2') }}"
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
    force: true