- name: Configure network interface auto
  notify: Reload networking
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "auto {{ interface_name }}"
    state: "{{ 'present' if (not 'auto' in pve_network_interfaces[interface_name] or pve_network_interfaces[interface_name].auto == true) else 'absent' }}"
    insertbefore: "^iface {{ interface_name }}"

- name: Configure network interface attributes
  notify: Reload networking
  community.general.interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ interface_name }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ pve_network_interfaces[interface_name] | dict2items | rejectattr('key', 'equalto', 'auto') }}"

- name: Flush handlers to apply network configuration immediately
  ansible.builtin.meta: flush_handlers