- name: Add kernel boot parameters
  notify:
    - Update initamfs image
    - Reboot machine
  ansible.builtin.replace:
    backup: true
    dest: /etc/kernel/cmdline
    regexp: '^(root=(?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  loop:
    - "intel-iommu=on"
    - "iommu=pt"
  when: pve_pci_passhthrough_enabled is defined and pve_pci_passhthrough_enabled

- name: Load required kernel modules
  notify:
    - Update initamfs image
    - Reboot machine
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "{{ item }}"
  loop:
    - vfio
    - vfio_iommu_type1
    - vfio_pci
    - vfio_virqfd
  when: pve_pci_passhthrough_enabled is defined and pve_pci_passhthrough_enabled
