- name: Assign scoped roles to users
  no_log: true
  ansible.builtin.lineinfile:
    path: /etc/pve/user.cfg
    create: false
    regex: "^acl:1:{{ permission.scope | default('/') }}:{{ user.username }}@{{ user.realm }}:(.*)"
    line: "acl:1:{{ permission.scope | default('/') }}:{{ user.username }}@{{ user.realm }}:{{ permission.roles | join(',') }}:"
    insertafter: "^user:.*"
  loop: "{{ user.permissions }}"
  loop_control:
    loop_var: permission
