- name: Update ZFS ARC max size for current boot
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/zfs.conf
    regexp: '^options zfs zfs_arc_max='
    line: "options zfs zfs_arc_max={{ pve_zfs_max_arc_size_gb * 1024 * 1024 * 1024 }}"
    create: true
    owner: root
    group: root
    mode: 0644

- name: Update ZFS ARC max size for subsequent boots
  copy:
    dest: /sys/module/zfs/parameters/zfs_arc_max
    content: "{{ pve_zfs_max_arc_size_gb * 1024 * 1024 * 1024 }}"
    force: false
    owner: root
    group: root
    mode: 0644
