# Common
ansible_host: 10.1.8.11
ansible_hostname: pve1-lab

# UPS
ups_name: dummy-ups1

# GetSSL
getssl_cron_renewal_hour: 16

# Monitoring
app_gatus_monitored_endpoints:
  - name: pve1 / ping
    group: Proxmox VE
    type: ping
  - name: pve1 / http
    group: Proxmox VE
    type: https
    host: pve1-lab.homecentr.one