# Common
ansible_host: 10.1.8.11
ansible_hostname: pve1-lab
fqdn: pve1-lab.homecentr.one

# UPS
ups_name: dummy-ups1

# Gluster
gluster_ip: 192.168.1.11
gluster_hostname: gfs-pve1-lab
gluster_fqdn: gfs-pve1-lab.homecentr.one
gluster_mount_host: pve1

# PVE
pve_pci_passhthrough_enabled: false

pve_network_interfaces:
  eth1:
    method: static
    address: 192.168.1.11/24
    auto: true

pve_vm_machines:
  - vmid: 101
    name: kube1-lab
    protection: false
    cloud_image_filename: debian-12.1.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size_gb: 32
    cpu_count: 1
    cpu_cores_per_cpu: 4
    min_memory: 4096
    max_memory: 4096
    nic_ipv4_address: 10.1.8.21
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.8.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

# ClamAV
# clamav_scanned_dirs:
# - /usr/local/gfs
