# Common
ansible_host: 10.1.8.12
ansible_hostname: pve2-lab
fqdn: pve2-lab.homecentr.one

network_interfaces:
  ens19:
    method: static
    address: 192.168.7.12/24
    auto: true

# UPS
ups_name: dummy-ups1

# Gluster
gluster_ip: 192.168.7.12
gluster_hostname: gfs-pve2-lab
gluster_fqdn: gfs-pve2-lab.homecentr.one
gluster_mount_host: pve2

# PVE
pve_pci_passhthrough_enabled: false

pve_vm_machines:
  - vmid: 201
    name: kube2-lab
    protection: false
    cloud_image_filename: debian-12.1.0.qcow2
    bios: efi
    shutdown_timeout_seconds: 120
    nic_bridge: vmbr0
    os_storage: local-zfs
    os_disk_size: 32G
    cpu_count: 1
    cpu_cores_per_cpu: 8
    min_memory: 8192
    max_memory: 15360
    nic_ipv4_address: 10.1.8.22
    nic_ipv4_subnet: 255.255.255.0
    nic_ipv4_gateway: 10.1.8.1
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

# ClamAV
# clamav_scanned_dirs:
# - /usr/local/gfs
