# Common
ansible_host: 10.1.8.12
ansible_hostname: pve2-lab
fqdn: pve2-lab.homecentr.one

network_interfaces:
  ens19:
    method: static
    address: 192.168.7.12/24
    auto: true

# UPS
ups_name: dummy-ups1

# nVidia drivers
nvidia_drivers_install_containers: true
