ansible_host: "{{ ipam.frigate }}"
ansible_hostname: "ct-frigate{{ env.suffix }}"

app_container_docker_support: true
app_container_network_interfaces:
  - name: eth0
    bridge: vmbr0
    ipv4_address: "{{ ipam.frigate }}/24"
    ipv4_gateway: "{{ subnets.services | ansible.utils.ipmath(1) }}"

app_container_pve_node: pve2
app_container_pve_ha_group_name: non-critical
app_container_pve_replication_nodes:
  - pve1

app_frigate_image_tag: 0.13.2

app_pihole_records:
  - hostname: "frigate{{ env.suffix }}"
    type: pomerium_proxy

app_pomerium_routes:
  - hostname: "frigate{{ env.suffix }}"
    target_port: 5000
    auth_mode: users

app_gatus_monitored_endpoints:
  - name: Web UI / container
    group: Frigate
    type: http
    host: "ct-frigate{{ env.suffix }}"
    port: 5000
  - name: Web UI / via proxy
    group: Frigate
    type: https-pomerium-proxy
    host: "frigate{{ env.suffix }}.homecentr.one"