ansible_host: "{{ subnets.services | ansible.utils.ipmath(67) }}"
ansible_hostname: "ct-mqtt{{ env.suffix }}"

app_container_memory: 512
app_container_storage_size_gb: 5
app_container_network_interfaces:
  - name: eth0
    bridge: vmbr0
    ipv4_address: "{{ subnets.services | ansible.utils.ipmath(67) }}/24"
    ipv4_gateway: "{{ subnets.services | ansible.utils.ipmath(1) }}"

app_container_pve_node: pve1
app_container_pve_ha_group_name: non-critical
app_container_pve_replication_nodes:
  - pve2

app_pihole_records:
  - hostname: "mqtt{{ env.suffix }}"
    type: ansible_host
