ansible_host: "{{ subnets.services | ansible.utils.ipmath(64) }}"
ansible_hostname: "ct-pihole{{ env.suffix }}"

app_container_nameserver: 1.1.1.1
app_container_memory: 512
app_container_storage_size_gb: 5
app_container_network_interfaces:
  - name: eth0
    bridge: vmbr0
    ipv4_address: "{{ subnets.services | ansible.utils.ipmath(64) }}/24"
    ipv4_gateway: "{{ subnets.services | ansible.utils.ipmath(1) }}"

app_container_pve_node: pve1
app_container_pve_ha_group_name: critical-priority-pve1
app_container_pve_replication_nodes:
  - pve2

app_pihole_version: 5.17.3
app_pihole_forwarders:
  - 1.1.1.1
  - 1.0.0.1

app_pomerium_routes:
  - hostname: "pihole{{ env.suffix }}"
    auth_mode: administrators

app_pihole_records:
  - hostname: "pihole{{ env.suffix }}"
    type: pomerium_proxy

app_gatus_monitored_endpoints:
  - name: Web UI
    group: Pi-hole
    type: https-pomerium-proxy
    host: "pihole{{ env.suffix }}.homecentr.one"
  - name: DNS
    group: Pi-hole
    type: dns
    host: "{{ subnets.services | ansible.utils.ipmath(64) }}"
    dns_query_name: "login{{ env.suffix }}.homecentr.one"
    dns_query_type: "A"
    dns_query_answer: "{{ subnets.services | ansible.utils.ipmath(66) }}"