ansible_host: "{{ ipam.pihole1 }}"
ansible_hostname: "ct-pihole1{{ env.suffix }}"

app_container_network_interfaces:
  - name: eth0
    bridge: vmbr0
    ipv4_address: "{{ ipam.pihole1 }}/24"
    ipv4_gateway: "{{ subnets.services | ansible.utils.ipmath(1) }}"

app_container_pve_node: pve1
app_container_pve_ha_group_name: critical-priority-pve1
app_container_pve_replication_nodes:
  - pve2

app_pomerium_routes:
  - hostname: "pihole1{{ env.suffix }}"
    auth_mode: administrators

app_pihole_records:
  - hostname: "pihole1{{ env.suffix }}"
    type: pomerium_proxy

app_gatus_monitored_endpoints:
  - name: pihole1 / Web UI
    group: Pi-hole
    type: https-pomerium-proxy
    host: "pihole1{{ env.suffix }}.homecentr.one"
  - name: pihole1 / DNS
    group: Pi-hole
    type: dns
    host: "{{ ipam.pihole1 }}"
    dns_query_name: "login{{ env.suffix }}.homecentr.one"
    dns_query_type: "A"
    dns_query_answer: "{{ ipam.pomerium }}"