# Common
ansible_host: "{{ ipam.pve1 }}"
ansible_hostname: "pve1{{ env.suffix }}"

# GetSSL
getssl_cron_renewal_hour: 16

app_pomerium_routes:
  - hostname: "pve{{ env.suffix }}"
    auth_mode: public # Proxmox has its own authentication
    protocol: https
    target_port: 8006
    tls_upstream_server_name: "pve{{ env.suffix }}.homecentr.one"
    backend:
      - "{{ ipam.pve1 }}"
      - "{{ ipam.pve2 }}"
      - "{{ ipam.pve3 }}"
    backend_lb_policy: RING_HASH

# DNS
app_pihole_records:
  - hostname: "pve{{ env.suffix }}"
    type: pomerium_proxy

# Monitoring
app_gatus_monitored_endpoints:
  - name: pve1 / ping
    group: Proxmox VE
    type: ping
    host: "pve1{{ env.suffix }}.homecentr.one"
  - name: pve1 / Web UI
    group: Proxmox VE
    type: https
    host: "pve1{{ env.suffix }}.homecentr.one"
  
  # Can check directly root because the site is not authenticated by pomerium
  - name: Balancing proxy / Web UI
    group: Proxmox VE
    type: https-pomerium-proxy
    host: "pve{{ env.suffix }}.homecentr.one"