# Common
ansible_host: "{{ ipam.pve1 }}"
ansible_hostname: "pve1{{ env.suffix }}"

# GetSSL
getssl_cron_renewal_hour: 16

# Monitoring
app_gatus_monitored_endpoints:
  - name: pve1 / ping
    group: Proxmox VE
    type: ping
    host: "pve1{{ env.suffix }}.homecentr.one"
  - name: pve1 / http
    group: Proxmox VE
    type: https
    host: "pve1{{ env.suffix }}.homecentr.one"