- name: Create etc directory
  ansible.builtin.file:
    path: /etc/coredns
    owner: coredns
    group: coredns
    mode: "0770"
    state: directory

- name: Create config file
  register: app_coredns_corefile
  ansible.builtin.copy:
    dest: /etc/coredns/Corefile
    owner: coredns
    group: coredns
    mode: "0660"
    content: "{{ lookup('template', 'corefile.j2') }}"