- name: "Create update-motd.d directory if doesn't exist"
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Clear pre-existing default scripts
  ansible.builtin.include_tasks:
    file: clear-defaults.yml

- name: Create common scripts
  ansible.builtin.include_tasks:
    file: setup-common-scripts.yml

- name: Create UPS (NUT) scripts
  ansible.builtin.include_tasks:
    file: setup-ups-scripts.yml
  when: motd_enable_ups_status

# ZFS
- name: Create ZFS scripts
  ansible.builtin.include_tasks:
    file: setup-zfs-scripts.yml
  when: motd_enable_zfs_status

- name: Clear ZFS scripts
  ansible.builtin.include_tasks:
    file: clear-zfs-scripts.yml
  when: not motd_enable_zfs_status

# HW
- name: Create HW related scripts
  ansible.builtin.include_tasks:
    file: setup-hw-scripts.yml
  when: motd_enable_hw_status

- name: Clear HW related scripts
  ansible.builtin.include_tasks:
    file: clear-hw-scripts.yml
  when: not motd_enable_hw_status

# Services
- name: Create services scripts
  ansible.builtin.include_tasks:
    file: setup-services-scripts.yml
  when: motd_services is defined and (motd_services | length) > 0

- name: Clear services scripts
  ansible.builtin.include_tasks:
    file: clear-services-scripts.yml
  when: (not motd_services is defined) or (motd_services | length) == 0

- name: Update PAM configuration to point to correct motd file
  ansible.builtin.replace:
    path: /etc/pam.d/sshd
    regexp: "motd=/run/motd.dynamic.new$"
    replace: "motd=/run/motd.dynamic"
