- name: Postmap sasl_passwd
  ansible.builtin.command: >
    postmap /etc/postfix/sasl_passwd

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: APT update
  ansible.builtin.apt:
    update_cache: true

- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update initamfs image
  ansible.builtin.command:
    cmd: update-initramfs -u -k all

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 500
  throttle: 1