- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Reload networking
  ansible.builtin.command:
    cmd: ifreload -a
  changed_when: true

- name: APT update
  ansible.builtin.apt:
    update_cache: true

- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update initamfs image
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  changed_when: true

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 500
  throttle: 1
