- name: Create config directory
  ansible.builtin.file:
    path: /etc/frigate
    owner: root
    group: root
    mode: "0750"
    state: directory

- name: Create config file
  register: app_frigate_config
  ansible.builtin.copy:
    dest: /etc/frigate/config.yml
    content: "{{ lookup('template', 'config.j2') }}"
    owner: root
    group: root
    mode: "0640"

- name: Create docker stack
  ansible.builtin.include_tasks:
    file: docker.yaml
