- name: Install Fleet CRDs
  run_once: true
  kubernetes.core.helm:
    state: present
    create_namespace: true
    release_name: fleet-crd
    release_namespace: cattle-fleet-system
    chart_ref: "https://github.com/rancher/fleet/releases/download/v{{ fleet_version }}/fleet-crd-{{ fleet_version }}.tgz"
    kubeconfig_path: "{{ fleet_kubeconfig_path }}"
    wait: true
    timeout: 5m0s

- name: Install Fleet Controllers
  run_once: true
  kubernetes.core.helm:
    state: present
    create_namespace: true
    release_name: fleet
    release_namespace: cattle-fleet-system
    chart_ref: "https://github.com/rancher/fleet/releases/download/v{{ fleet_version }}/fleet-{{ fleet_version }}.tgz"
    kubeconfig_path: "{{ fleet_kubeconfig_path }}"
    wait: true
    timeout: 5m0s