- name: Deploy global resources
  run_once: true
  k8s:
    kubeconfig: "{{ local_storage_kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
  with_items:
    - service-account.yml.j2
    - cluster-role.yml.j2
    - cluster-role-binding.yml.j2
    - role.yml.j2
    - role-binding.yml.j2
    - network-policy.yml.j2
  
- name: Deploy volume resources
  ansible.builtin.include_tasks:
    file: volume.yml
  loop: "{{ local_storage_volumes }}"
  loop_control:
    loop_var: volume
  