- name: "Deploy resource for volume {{ volume.name }}"
  run_once: true
  k8s:
    kubeconfig: "{{ local_storage_kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
  with_items:
    - config-map.yml.j2
    - deployment.yml.j2
    - storage-class.yml.j2