all:
  children:
    pve_nodes:
      hosts:
        lab-pve1:
        lab-pve2:
        lab-pve3:
    k8s_nodes:
      hosts:
        lab-kube1:
        lab-kube2:
        lab-kube3:
    bare_metal_nodes:
      hosts:
        lab-pve1:
        lab-pve2:
        lab-pve3:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            lab-pve1:
            lab-pve2:
            lab-pve3:
        gluster_clients:
          hosts:
            lab-pve1:
            lab-pve2:
            lab-pve3:
            lab-kube1:
            lab-kube2:
            lab-kube3:
