all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    k8s_nodes:
      hosts:
        kube1:
        kube2:
        kube3:
    bare_metal_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            pve1:
            pve2:
            pve3:
        gluster_clients:
          hosts:
            kube1:
            kube2:
            kube3:
    nvidia_gpu_nodes:
      hosts:
        pve1:
        pve2:
        kube1:
        kube2: