all:
  children:
    pve_nodes:
      hosts:
        pve1-lab:
        pve2-lab:
        pve3-lab:
    k8s_nodes:
      hosts:
        kube1-lab:
        kube2-lab:
        kube3-lab:
    bare_metal_nodes:
      hosts:
        pve1-lab:
        pve2-lab:
        pve3-lab:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            pve1-lab:
            pve2-lab:
            pve3-lab:
        gluster_clients:
          hosts:
            pve1-lab:
            pve2-lab:
            pve3-lab:
            kube1-lab:
            kube2-lab:
            kube3-lab:
