all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    containers:
      hosts:      
        frigate:
        homepage:
        monitoring:
        mqtt:
        pihole:
        pomerium:
        unifi_controller:
      children:
        cloudflared_containers:
          hosts:
            cloudflared1:
            cloudflared2:
