---
all:
  children:
    pve_nodes:
      hosts:
        lab-pve1:
        lab-pve2:
    # k8s_nodes:
    #   hosts:
    #     lab-kube1:
    #     lab-kube2:
    ups_masters:
      hosts:
        lab-pve1:
    ups_slaves:
      hosts:
        lab-pve2:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            lab-pve1:
            lab-pve2:
        gluster_clients:
          hosts:
            lab-pve1:
            lab-pve2:
            # lab-kube1:
            # lab-kube2:
