all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    containers:
      hosts:
        pihole:
        pomerium:
        mqtt:
        monitoring:
        frigate:
      children:
        cloudflared_containers:
          hosts:
            cloudflared1:
            cloudflared2:
