pve_cluster_firewall_enabled: false

pve_cluster_firewall_aliases:
  - name: some-alias
    cidr: 10.1.3.0/24 # must be an ip or cidr => cidr

pve_cluster_firewall_ipsets:
  - name: My set
    items:
      - type: alias
        name: some-alias
      - type: cidr
        cidr: 10.1.8.0/24 # type cidr should be default

pve_cluster_firewall_security_groups:
  - name: my-group
    rules:
      - direction: IN
        action: ACCEPT
        macro: SSH
        source:
          type: ipset
          name: some-ipset
        destination: 10.1.8.0/24 # optional

      - enabled: false # default = true
        direction: IN
        action: ACCEPT
        source_port: 25
        destination_port: http
        source: # might be: ipset (+<name>), alias (dc/<name>), comma-separated list of ips or most likely also a cidr
          type: alias
          name: some-alias
        destination: 10.1.8.0/24