# This is required for VNC proxy between the nodes
ssh_allow_root_login_trusted_clients:
  - pve1
  - pve2
  - pve3

pve_zfs_max_arc_size_gb: 0.5

# TODO: Move this to a common role !!!
pve_domain: homecentr.one
pve_nameservers:
  - 1.1.1.1
  - 1.0.0.1

pve_smtp_host: 10.1.8.130
pve_smtp_port: 25
pve_smtp_tls: false

pve_vm_cloud_images:
  - filename: debian-12.1.0.qcow2
    url: https://cloud.debian.org/images/cloud/bookworm/20230723-1450/debian-12-generic-amd64-20230723-1450.qcow2
    format: qcow2
    checksum: sha512:398589d1baa0c1a79358d2c6f14ba9212c25419df2693c513645cb493e15e19952f873703f27d87c491272a478f51a957fb26b21f485dca5933db6be37207d59
