- name: Create override directory
  ansible.builtin.file:
    dest: /etc/systemd/system/pomerium.service.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create override file to allow usage of port 443
  ansible.builtin.copy:
    dest: /etc/systemd/system/pomerium.service.d/override-port.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Service]
      AmbientCapabilities=CAP_NET_BIND_SERVICE

- name: (Re)start service
  ansible.builtin.systemd_service:
    name: pomerium
    enabled: true
    daemon_reload: true
    state: "{{ 'restarted' if app_pomerium_config_file.changed else 'started' }}"
