- name: Restart server daemon
  register: gluster_restart
  until: gluster_restart.status.ActiveState == "active"
  delay: 20
  retries: 15
  throttle: 1
  ansible.builtin.service:
    name: glusterd
    state: restarted
    enabled: true
