- name: Fetch kubeaudit checksums
  ansible.builtin.uri:
    url: https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit_0.20.0_checksums.txt
    return_content: true
  register: kubeaudit_checksums

- name: Download kubeaudit
  ansible.builtin.get_url:
    url: https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit_0.20.0_linux_amd64.tar.gz
    checksum: >
      "sha256:{{ (kubeaudit_checksums.content | regex_search('(?P<checksum>[a-z0-9]+)\\W*kubeaudit_.*_linux_amd64', '\\g<checksum>', multiline=True)) }}"
    dest: /tmp/kubeaudit.tar.gz
    mode: 0755
    owner: root
    group: root

- name: "Extract archive"
  ansible.builtin.unarchive:
    src: /tmp/kubeaudit.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - "--wildcards"
      - "kubeaudit"
    remote_src: true

- name: Rename file to be compatible with kubectl plugin
  ansible.builtin.copy:
    src: /usr/local/bin/kubeaudit
    dest: /usr/local/bin/kubectl-audit
    mode: 0755
    owner: root
    group: root
    remote_src: true

- name: Remote temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/kubeaudit.tar.gz"
    - "/usr/local/bin/kubeaudit"
