- name: Install python modules
  ansible.builtin.apt:
    name: 
      - python3-passlib
      - python3-cryptography

- name: Get certificates default directory
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      openssl version -d | cut -d'"' -f2
  args:
    executable: /bin/bash
  register: gluster_openssl_dir
  changed_when: false

- name: Copy CA certificate
  register: gluster_tls_ca
  ansible.builtin.copy:
    dest: "{{ gluster_openssl_dir.stdout }}/glusterfs.ca"
    content: "{{ gluster_ca.public_key }}"
    owner: root
    group: root
    mode: 0600
    force: true

- name: Generate private key
  register: gluster_tls_private_key
  community.crypto.openssl_privatekey:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    size: "{{ gluster_node_tls_key_size }}"

- name: Create certificate signing request
  community.crypto.openssl_csr:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.csr"
    privatekey_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    common_name: "{{ gluster_node_hostname }}"
    subject_alt_name: "{{ gluster_node_additional_names | map('regex_replace', '(.*)', 'DNS:\\1') | join(',') }}"

- name: Generate a node certificate
  register: gluster_tls_cert
  community.crypto.x509_certificate:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.pem"
    privatekey_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    csr_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.csr"
    ownca_not_after: "+{{ gluster_tls_certificate_validity_days }}d"
    ownca_content: "{{ gluster_ca.public_key }}"
    ownca_privatekey_content: "{{ gluster_ca.private_key }}"
    provider: ownca

- name: Enable Gluster TLS (Create dir)
  ansible.builtin.file:
    path: /var/lib/glusterd
    state: directory
    owner: root
    group: root
    mode: 0744

- name: Enable Gluster TLS
  register: gluster_tls_enabled
  ansible.builtin.file:
    path: /var/lib/glusterd/secure-access
    access_time: preserve # to avoid changing the file when it already exists (causes additional daemon restarts)
    modification_time: preserve
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Restart server daemon  # noqa no-handler include_tasks cannot notify a handler
  register: gluster_restart
  until: gluster_restart.status.ActiveState == "active"
  delay: 20
  retries: 15
  throttle: 1
  when: (gluster_tls_enabled.changed
    or gluster_tls_cert.changed
    or gluster_tls_private_key.changed
    or gluster_tls_ca.changed)
    and (gluster_server_restart | default(false))
  ansible.builtin.service:
    name: glusterd
    state: restarted
    enabled: true
