- name: Install required pip modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: cryptography

- name: Get certificates default directory
  ansible.builtin.shell:
    cmd: "openssl version -d | cut -d'\"' -f2"
  register: gluster_openssl_dir
  changed_when: false

- name: Copy CA certificate
  ansible.builtin.copy:
    dest: "{{ gluster_openssl_dir.stdout }}/glusterfs.ca"
    content: "{{ gluster_ca_public_key }}"
    owner: root
    group: root
    mode: 0600
    force: true

- name: Generate private key
  register: gluster_private_key
  community.crypto.openssl_privatekey:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    size: "{{ gluster_node_tls_key_size }}"

- name: Create certificate signing request
  community.crypto.openssl_csr:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.csr"
    privatekey_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    common_name: "{{ gluster_node_hostname }}"
    subject_alt_name: "{{ gluster_node_additional_names | map('regex_replace', '(.*)', 'DNS:\\1') | join(',') }}"

- name: Generate a node certificate
  register: gluster_cert
  community.crypto.x509_certificate:
    path: "{{ gluster_openssl_dir.stdout }}/glusterfs.pem"
    privatekey_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.key"
    csr_path: "{{ gluster_openssl_dir.stdout }}/glusterfs.csr"
    ownca_not_after: "+{{ gluster_tls_certificate_validity_days }}d"
    ownca_content: "{{ gluster_ca_public_key }}"
    ownca_privatekey_content: "{{ gluster_ca_private_key }}"
    provider: ownca

- name: Enable Gluster TLS (Create dir)
  ansible.builtin.file:
    path: /var/lib/glusterd
    state: directory
    owner: root
    group: root
    mode: 0744

- name: Enable Gluster TLS
  register: gluster_secure_access
  ansible.builtin.file:
    path: /var/lib/glusterd/secure-access
    access_time: preserve # to avoid changing the file when it already exists (causes additional daemon restarts)
    modification_time: preserve
    state: touch
    owner: root
    group: root
    mode: 0644
