all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    k8s_cluster:
      children:
        masters:
          hosts:
            pve1:
            pve2:
            pve3:
        workers:
          hosts:
            pve1:
            pve2:
            pve3:
    nvidia_gpu_nodes:
      hosts:
        pve1:
        pve2: