all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    k8s_cluster:
      children:
        masters:
          hosts:
            kube1:
            kube2:
            kube3:
        workers:
          hosts:
            kube1:
            kube2:
            kube3:
    bare_metal_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    nvidia_gpu_nodes:
      hosts:
        pve1:
        pve2:
        kube1:
        kube2: