app_coredns_version: 1.11.1

app_coredns_forwarders_tls_servername: cloudflare-dns.com

app_coredns_forwarders:
  - 1.1.1.1
  - 1.0.0.1

app_coredns_records:
  - name: dns1-lab.homecentr.one
    value: 10.1.8.128
  - name: dns2-lab.homecentr.one
    value: 10.1.8.129
  - name: login-lab.homecentr.one
    value: 10.1.8.132
  - name: gatus-lab.homecentr.one
    value: 10.1.8.132