gluster_volumes:
  - name: k3s-services
    mount_path: /mnt/gfs/k3s-services
    storage_bricks:
      - host: lab-pve1
        path: /usr/local/gfs/k3s-services/brick0
      - host: lab-pve2
        path: /usr/local/gfs/k3s-services/brick0
    arbiter_bricks:
      - host: lab-pve3
        path: /usr/local/gfs/k3s-services/brick0
    replicas: 2
    arbiters: 1
    quotas: true
    allowed_clients:
      - lab-kube1
      - lab-kube2
      - lab-kube3
      - lab-pve1
      - lab-pve2
      - lab-pve3

# TODO: k3s-user-data
# TODO: k3s-nvr
