gluster_volumes:
  - name: k3s-services2
    mount_path: /mnt/gfs/k3s-services2
    storage_bricks:
      # Replica set
      - host: pve1
        path: /usr/local/gfs/k3s-services2/brick0
      - host: pve2
        path: /usr/local/gfs/k3s-services2/brick0

      # Replica set
      - host: pve1
        path: /usr/local/gfs/k3s-services2/brick1
      - host: pve2
        path: /usr/local/gfs/k3s-services2/brick1
    arbiter_bricks:
      - host: pve3
        path: /usr/local/gfs/k3s-services2/brick0
      - host: pve3
        path: /usr/local/gfs/k3s-services2/brick1
    replicas: 2
    arbiters: 1
    quota: 10.0GB
    force: true
    allowed_clients:
      - kube1
      - kube2
      - kube3
      - pve1
      - pve2
      - pve3

