- name: "Install gpg (required to add apt key)"
  ansible.builtin.apt:
    name: gpg
    state: present

- name: "Add Lynis repository apt key"
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 013baa07180c50a7101097ef9de922f1c2fde6c4

- name: "Install apt https support"
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: "Add Lynis repository"
  ansible.builtin.apt_repository:
    repo: "deb https://packages.cisofy.com/community/lynis/deb/ stable main"
    state: present

- name: "Install Lynis"
  ansible.builtin.apt:
    name: lynis
    update_cache: true
