- name: Create firewall config file if it does not exist
  run_once: true
  ansible.builtin.file:
    path: /etc/pve/firewall/cluster.fw
    state: touch

- name: Configure cluster firewall
  ansible.builtin.import_role:
    name: "{{ role_path }}/../pve_firewall_common"
  vars:
    pve_firewall_default_scope: dc
    pve_firewall_filepath: /etc/pve/firewall/cluster.fw
    pve_firewall_aliases: "{{ pve_cluster_firewall_aliases }}"
    pve_firewall_ipsets: "{{ pve_cluster_firewall_ipsets }}"
    pve_firewall_rules: "{{ pve_cluster_firewall_rules }}"
    pve_firewall_enabled: "{{ pve_cluster_firewall_enabled }}"
    pve_firewall_security_groups: "{{ pve_cluster_firewall_security_groups }}"