- name: Create ZFS volumes for Longhorn
  community.general.zfs:
    name: "{{ zvol.name }}"
    state: present
    extra_zfs_properties:
      volsize: "{{ zvol.size }}"

- name: Create xfs file system in zvols for Longhorn
  community.general.filesystem:
    dev: "/dev/zvol/{{ zvol.name }}"
    fstype: xfs
    state: present

- name: Mount zvol
  ansible.posix.mount:
    src: "/dev/zvol/{{ zvol.name }}"
    path: "{{ zvol.mountpoint }}"
    fstype: xfs
    opts: noatime,discard
    state: mounted