- name: Install required pip modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: proxmoxer

- name: Download installation cloud images
  ansible.builtin.include_tasks:
    file: images.yml

- name: Create virtual machines
  ansible.builtin.include_tasks:
    file: vm.yml
  vars:
    vm: "{{ item }}"
  when: pve_vm_machines is defined
  with_items: "{{ pve_vm_machines }}"

# - name: Download Ubuntu cloud image
#   get_url:
#     url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
#     dest: /tmp/focal-server-cloudimg-amd64.img

# - name: Download Debian cloud image
#   get_url:
#     url: https://cloud.debian.org/cdimage/cloud/bullseye/20221020-1174/debian-11-generic-amd64-20221020-1174.qcow2
#     dest: /tmp/debian.qcow2

# - name: Debug
#   delegate_to: localhost
#   become: false
#   copy:
#     dest: /tmp/keys.txt
#     content: "{{ users_admin_public_keys | join('\n') }}"
#     force: true

# - name: Create empty VM using Cloud-Init
#   community.general.proxmox_kvm:
#     vmid: 100
#     node: "{{ ansible_hostname }}"
#     api_user: root@pam
#     api_password: "{{ users_root_password }}"
#     api_host: 127.0.0.1
#     name: testvm-template # TODO: VM Name
#     scsihw: virtio-scsi-pci
#     kvm: true
#     ide:
#       ide2: 'local-zfs:cloudinit,format=raw'
#     bootdisk: scsi0
#     ciuser: "{{ users_admin_username }}"
#     cipassword: hallowelt # TODO: Remove password
#     sshkeys: "{{ users_admin_public_keys | join('\n') }}"
#     net:
#       net0: 'virtio,bridge=vmbr0'
#     ipconfig:
#       ipconfig0: 'ip=10.1.8.50/24,gw=10.1.8.1'
#     nameservers:
#       - 1.1.1.1
#       - 1.0.0.1
#     proxmox_default_behavior: compatibility
#     # TODO: System disk should have a size limit
#     # TODO: How to make the disk bigger ???


# - name: Import init disk
#   ansible.builtin.command:
#     #cmd: "qm importdisk 100 /tmp/focal-server-cloudimg-amd64.img local-zfs"
#     cmd: "qm importdisk 100 /tmp/debian.qcow2 local-zfs --format qcow2"
#     creates: "/dev/zvol/rpool/data/vm-100-disk-0"

#     #  && qm resize 100 scsi0 20G
#     # when changed ???

# - name: Attach base image disk
#   ansible.builtin.lineinfile:
#     path: /etc/pve/local/qemu-server/100.conf
#     regexp: '^scsi0:.*'
#     line: 'scsi0: local-zfs:vm-100-disk-0' # TODO: Add size, add ssd emulation

# - name: Remove unused disk reference to base disk
#   ansible.builtin.lineinfile:
#     path: /etc/pve/local/qemu-server/100.conf
#     regexp: '^unused\d+:.*'
#     state: absent
