- name: Install required pip modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: proxmoxer

- name: Download installation images
  ansible.builtin.include_tasks:
    file: images.yml

- name: Create virtual machines
  ansible.builtin.include_tasks:
    file: vm.yml
