- name: Create virtual machine
  community.general.proxmox_kvm:
    vmid: "{{ vm.vmid }}"
    proxmox_default_behavior: no_defaults
    node: "{{ ansible_hostname }}"
    kvm: true
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    name: "{{ vm.name }}"
    protection: "{{ vm.protection | default(true) }}"
    acpi: "{{ vm.acpi | default(true) }}"
    autostart: "{{ vm.autostart | default(true) }}"
    onboot: "{{ vm.onboot | default(true) }}"
    ostype: "{{ vm.ostype | default('l26') }}"
    boot: "{{ vm.boot_order | default('cd') }}"
    ciuser: "{{ users_admin_username }}"
    sshkeys: "{{ users_admin_public_keys | join('\n') }}"
    bios: "{{ 'seabios' if (vm.bios | default('bios')) != 'efi' else 'ovmf' }}"
    startup: "down={{ vm.shutdown_timeout_seconds }}"
    # required due to a bug: https://forum.proxmox.com/threads/kernel-panic-after-resizing-a-clone.93738/
    # which causes kernel panic after resizing the os disk
    serial:
      serial0: socket
    scsi:
      scsi0: 'local-zfs:cloudinit,format=raw'
    net:
      net0: "virtio,bridge={{ vm.nic_bridge }}"
    ipconfig:
      ipconfig0: "ip={{ (vm.nic_ipv4_address + '/' + vm.nic_ipv4_subnet) | ansible.utils.ipaddr('host/prefix') }},gw={{ vm.nic_ipv4_gateway }}"
    nameservers: "{{ vm.nameservers }}"
    efidisk0: "{{ ({'storage': vm.os_storage, 'format': 'raw', 'efitype': '4m', 'pre_enrolled_keys': false}) if (vm.bios | default('bios')) == 'efi' else none }}" # noqa yaml[line-length]
    scsihw: virtio-scsi-pci
    bootdisk: scsi1
    tablet: false
    cpu: "kvm64"
    vcpus: "{{ vm.cpu_count }}"
    cores: "{{ vm.cpu_cores_per_cpu }}"
    memory: "{{ vm.min_memory }}"
    balloon: "{{ vm.max_memory }}"
    state: present

- name: Import disk from cloud image
  community.general.proxmox_disk:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    disk: scsi1
    import_from: "/var/lib/vz/images/{{ vm.cloud_image_filename }}"
    storage: "{{ vm.os_storage }}"
    ssd: true
    state: present

- name: Resize imported system disk
  community.general.proxmox_disk:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    disk: scsi1
    size: 25G
    state: resized

- name: Start VM
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    node: "{{ ansible_hostname }}"
    state: started

- name: Wait for VM to start responding on SSH
  ansible.builtin.wait_for:
    host: "{{ vm.nic_ipv4_address }}"
    port: 22
    delay: 20
    timeout: 300
    sleep: 5
    msg: "VM {{ vm.name }} did not start responding on SSH in time."
