- name: Ensure the aliases section
  run_once: true
  ansible.builtin.lineinfile:
    path: "{{ pve_firewall_filepath }}"
    create: false
    line: "[ALIASES]"
    state: present

- name: Configure aliases
  run_once: true
  loop: "{{ pve_firewall_aliases | default([]) }}"
  loop_control:
    loop_var: alias
  ansible.builtin.lineinfile:
    path: "{{ pve_firewall_filepath }}"
    create: false
    regex: "^{{ alias.name }} .*"
    line: "{{ alias.name }} {{ alias.cidr }}"
    firstmatch: true
    insertafter: "[ALIASES]"
    state: present
