- name: Validate aliases
  run_once: true
  loop: "{{ pve_firewall_aliases | default([]) }}"
  loop_control:
    loop_var: alias
  ansible.builtin.assert:
    quiet: true
    that:
      - (alias.name | regex_search("[A-Za-z][A-Za-z0-9\-\_]+")) == alias.name
      - (alias.name | length) <= 64

- name: Validate ipsets
  run_once: true
  loop: "{{ pve_firewall_ipsets | default([]) }}"
  loop_control:
    loop_var: ipset
  ansible.builtin.assert:
    quiet: true
    that:
      - (ipset.name | regex_search("[A-Za-z][A-Za-z0-9\-\_]+")) == ipset.name
      - (ipset.name | length) <= 64

- name: Validate security groups
  run_once: true
  loop: "{{ pve_firewall_security_groups | default([]) }}"
  loop_control:
    loop_var: group
  ansible.builtin.assert:
    quiet: true
    that:
      - (group.name | regex_search("[A-Za-z][A-Za-z0-9\-\_]+")) == group.name
      - (group.name | length) <= 18

- name: Update firewall file
  run_once: true
  ansible.builtin.copy:
    dest: "{{ pve_firewall_filepath }}"
    mode: "0640"
    owner: root
    group: www-data
    force: true
    content: "{{ lookup('template', 'firewall-file.j2') }}"
