- name: Ensure the rules section
  run_once: true
  ansible.builtin.lineinfile:
    path: "{{ pve_firewall_filepath }}"
    create: false
    line: "[RULES]"
    state: present

- name: Configure rules
  run_once: true
  loop: "{{ pve_firewall_rules | default([]) }}"
  loop_control:
    loop_var: rule
  ansible.builtin.lineinfile:
    path: "{{ pve_firewall_filepath }}"
    create: false
    line: "{{ lookup('template', 'firewall-rule.j2', template_vars=dict(rule=rule, default_scope='dc')) }}"
    firstmatch: true
    insertafter: "[RULES]"
    state: present