- name: Configure security group
  run_once: true
  loop: "{{ pve_firewall_security_groups | default([]) }}"
  loop_control:
    loop_var: group
  ansible.builtin.blockinfile:
    path: "{{ pve_firewall_filepath }}"
    create: false
    prepend_newline: true
    state: present
    marker: "# {mark} Ansible managed group ({{ group.name }})"
    block: "{{ lookup('template', 'security-group.j2', template_vars=dict(group=group, default_scope=pve_firewall_default_scope)) }}"
