k3s_cluster_secret: ENC[AES256_GCM,data:wWyLTLt3pKC0yZDzXVa4t2w2X5cGUav5QXA=,iv:7W9A9F+a/YONo44IPgzu914Rwr9RuLYZ4Bt5qhRE+78=,tag:+rJcWznLySjRrCWHhImctQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zw6c356patclh7q8cq5a99cghpzmnufgtwfaa0tmcg87a038d9ms4xpytn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL291aEpIamluU0UyWEpY
            dEJ6b3MyQ3ZFZHBONDhaQXZ1ek42OFN5b0gwCitvcS9abHVMWjRmNzU2cmd3OFlN
            UXh3dXZPRTYxdDFpSnFsanFwRXh1TmsKLS0tIGc3bTdQRVhvMXRGODczRjZTbnJa
            WHdnQWdTckVpZnNHK1V4RmxyT2p4WnMKSDzkHWfHgY44/tD7MBfE16zaqaeHwtqx
            pyVUWJGnzSoV2RJjMjvoAMaUOVNtgJjedAKIDlR8WZfpiQ0Bbu6zTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T21:49:11Z"
    mac: ENC[AES256_GCM,data:UbT8E5Z7+V+IvxB0SL/dLPZTUcVPZtGmdtAtPqu6ifDgHuUQE7GJN5yv0rmoRKO96WalV5pz7qiYiNGdcC+aYM0hZ833hhzO182Az2JbuLHSiCWeIUdrQBY4L8G2knAg1V1Xj4PhGq2jPVa0PEmPi5tLpqEonOlWT11zog9mV2c=,iv:bNfpoqGVA5C6oiOiTAtQJmJm2rnsUVtcTtiLFy9nHgg=,tag:ctQqOArV1MyEZxvr//AODw==,type:str]
    pgp:
        - created_at: "2023-06-05T09:02:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Pg+ndCcR5CAQ/+OQQREZEVqKTnkXOlcAupARoWRaFbU3FdPfRStqDi9q+k
            5AJiDcWzwzVV7REJ2/cNpv38xb5USTaS4ZrPBBF7oy+H5e7ybiEaqrrUoBsth19G
            pN1zZpuXu4nljhth4RIdcrbt5N/m3Cu6QYEi84BFAIdU9biakdo6Yym/gtN29fJU
            r/VViSAaJa/phlEBDWccsm+AsjA/hgDI9fTTOX3FFLA/k82dPkPkUHZzdtozXmZs
            C8ulf8VrtdTT7uAnpBXbu8SRt2oNqC4NRAPXJvu1DEdGJ3TL7RpCsarkQ5GpFRD/
            Dgw8K7bIHCmIPNPcaKfDF+DEpOsXDUQ+dyq8Tkw4+F40RhG9EApVxhZqj95n+uIN
            +j7WSyIVRyECZBGZpj9MdSHJQ+ObWA8MMHP3F4anbNYkg9HNcggs1gPeokkUuqKo
            P+6FpY7H1knzicepK+uGMpirhBHw1tMEo/tD3UMzoM5TRi7xy8jZBwqpGvF8kddE
            yL7WJE567PxbwMDgxcDJ/e+KHpQXoVTTGRL7NTN10gpxZehWMGTDUXXt0XWRKpYx
            5jmBCT7Tt1tGpTqq0Su3AG5h7Yj3+cYJj76XPUiPwwK7tQxSAW2/sjp2OEh4AIWw
            1+Vxut/zjvqkTHTRQ6Mg+iaamVt217NerRWIAzu3HGC8ON8wdXWjo7e4aarpz6TS
            XAHfR34JwsoKFJT4Risbv1gputNimbv/R6X5Y91yE64qlRBZql9bO6Z19nL7Xr44
            tF+EQZ6VdP8UHKNNbeMuGHSVpqsWENLFiruz2R1rCQmJ1c0dwEW8oEwJ9QKV
            =nkIf
            -----END PGP MESSAGE-----
          fp: 2D1D9C803F35BBC24014C3906601E1EB2454827F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
