- name: Load kube config
  ansible.builtin.slurp:
    src: "{{ kubeconfig_path }}"
  register: kubeconfig

- name: Create .kube directory
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "$HOME/.kube"
    state: directory
    mode: 0700

- name: Store kubeconfig on local workstation
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.copy:
    dest: "$HOME/.kube/config"
    content: "{{ kubeconfig.content | b64decode }}"
    mode: 0600
    force: true
