- name: restart ups_server
  service:
    name: "nut-server"
    state: "restarted"

- name: restart ups_monitor
  service:
    name: "nut-monitor"
    state: "restarted"

- name: restart ups_driver
  service:
    name: "nut-driver"
    state: "restarted"