- name: Add host entries for glusterfs servers (for servers)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].gluster_ip | replace('.', '\\.') }}\\W+{{ hostvars[item].gluster_hostname | replace('.', '\\.') }}\\W+{{ hostvars[item].gluster_fqdn | mandatory | replace('.', '\\.') }}\\W*$" # noqa yaml[line-length]
    line: "{{ hostvars[item].gluster_ip }} {{ hostvars[item].gluster_hostname }} {{ hostvars[item].gluster_fqdn }}"
  with_items: "{{ groups['gluster_servers'] }}"
