all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    containers:
      hosts:      
        frigate:
        homepage:
        monitoring:
        mqtt:
        pomerium:
        smtp_relay:
        unifi_controller:
      children:
        cloudflared:
          hosts:
            cloudflared1:
            cloudflared2:
        pihole:
          hosts:
            pihole1:
            pihole2:
