- name: Install required packages
  ansible.builtin.apt:
    name:
      - open-iscsi
    state: present

- name: Start iscsi daemon
  ansible.builtin.service:
    name: iscsid
    enabled: true
    state: started