- name: Install python for kubernetes management
  ansible.builtin.apt:
    name:
      - python3-kubernetes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - jq
      - nfs-common
    state: present

- name: Configure sysctls
  ansible.builtin.include_tasks:
    file: sysctls.yaml

- name: Install iscsi
  ansible.builtin.include_tasks:
    file: iscsi.yaml

- name: Install kubectl
  ansible.builtin.include_tasks:
    file: kubectl.yaml

- name: Install rke2 cluster
  ansible.builtin.import_role:
    name: lablabs.rke2
  tags:
    - rke2
  vars:
    rke2_type: server # All nodes are servers
    rke2_token: "{{ k8s_cluster_token }}"

    rke2_ha_mode: true
    rke2_ha_mode_kubevip: true
    rke2_ha_mode_keepalived: false
    rke2_kubevip_cloud_provider_enable: true
    rke2_kubevip_svc_enable: "true"

    rke2_kubevip_image: "{{ k8s_cluster_kubevip_image }}"
    rke2_kubevip_cloud_provider_image: "{{ k8s_cluster_kubevip_cloud_provider_image }}"

    rke2_api_ip: "{{ k8s_cluster_kubeapi_vip }}"
    rke2_drain_node_during_upgrade: true
    
    rke2_version: "{{ k8s_cluster_rke2_version }}"

    rke2_disable:
      - rke2-ingress-nginx
      - rke2-metrics-server

    rke2_server_options:
      - "cluster-cidr: {{ k8s_cluster_cluster_cidr }}" 
      - "service-cidr: {{ k8s_cluster_service_cidr }}" 

    rke2_loadbalancer_ip_range:
      range-global: "{{ k8s_cluster_kubevip_dynamic_range }}"

    rke2_kubevip_args: 
      - param: svc_election
        value: "'true'"
      # - param: enable_node_labeling
      #   value: "'true'"
      # - param: onlyAllowTrafficServicePorts
      #   value: true

    rke2_custom_manifests:
      - rke2-canal-customize.yaml
      - rke2-calico-apiserver.yaml
      - rke2-calico-apiserver-secret.yaml

# - name: Load kubeconfig
#   run_once: true
#   ansible.builtin.slurp:
#     src: /etc/rancher/rke2/rke2.yaml
#   register: k8s_cluster_kubeconfig

# - debug:
#     msg: "{{ k8s_cluster_kubeconfig.content | b64decode }}"

- name: Patch calico apiservice
  run_once: true
  kubernetes.core.k8s_json_patch:
    kind: APIService
    name: v3.projectcalico.org
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    patch:
      - op: replace
        path: /spec/caBundle
        value: "{{ k8s_cluster_calico_apiserver_public_key | b64encode }}"

