- name: Touch config files first to make it work with proxmox corosync
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
  loop:
    - /etc/pve/sdn/zones.cfg
    - /etc/pve/sdn/vnets.cfg
    - /etc/pve/sdn/subnets.cfg

- name: Configure zones
  ansible.builtin.copy:
    dest: /etc/pve/sdn/zones.cfg
    owner: root
    group: www-data
    mode: "0640"
    force: true
    content: "{{ lookup('template', 'zones.j2') }}"

- name: Configure vnets
  ansible.builtin.copy:
    dest: /etc/pve/sdn/vnets.cfg
    owner: root
    group: www-data
    mode: "0640"
    force: true
    content: "{{ lookup('template', 'vnets.j2') }}"

- name: Configure subnets
  ansible.builtin.copy:
    dest: /etc/pve/sdn/subnets.cfg
    owner: root
    group: www-data
    mode: "0640"
    force: true
    content: "{{ lookup('template', 'subnets.j2') }}"