- name: Install required packages
  ansible.builtin.apt:
    name: libpve-network-perl
    state: present

- name: Verify SDN is enabled
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    create: false
    line: "source /etc/network/interfaces.d/*"

- name: Update config files
  run_once: true
  ansible.builtin.include_tasks:
    file: configs.yaml

- name: Update IPAM
  run_once: true
  ansible.builtin.include_tasks:
    file: ipam.yaml

- name: Apply changes to the whole cluster
  changed_when: true
  ansible.builtin.command:
    cmd: pvesh set /cluster/sdn
