- name: Validate vnet name length
  ansible.builtin.assert:
    that: vnet.name | length <= 9  # total 15 with vxlan_ prefix
    msg: VNet name must be 9 characters or less

- name: Configure vnet
  ansible.builtin.blockinfile:
    path: /etc/pve/sdn/vnets.cfg
    create: true
    owner: root
    group: www-data
    mode: "0640"
    marker: "# {mark} Ansible managed vnet {{ vnet.name }}"
    block: |
      vnet: {{ vnet.name }}
            zone {{ zone.name }}
            tag {{ vnet.tag }}

- name: Configure subnet
  loop: "{{ vnet.subnets }}"
  loop_control:
    loop_var: subnet
  ansible.builtin.include_tasks:
    file: subnet.yaml