- name: Configure zome
  ansible.builtin.blockinfile:
    path: /etc/pve/sdn/zones.cfg
    create: true
    owner: root
    group: www-data
    mode: "0640"
    marker: "# {mark} Ansible managed vxlan {{ zone.name }}"
    block: |
      vxlan: {{ zone.name }}
             peers {{ zone.peer_hosts | map('extract', hostvars, 'ansible_host') | join(',') }}
             ipam {{ zone.ipam | default('pve') }}

- name: Configure vnets
  loop: "{{ zone.vnets }}"
  loop_control:
    loop_var: vnet
  ansible.builtin.include_tasks:
    file: vnet.yaml