- name: Fetch kubescape checksum
  ansible.builtin.uri:
    url: https://github.com/kubescape/kubescape/releases/latest/download/kubescape-ubuntu-latest-sha256
    return_content: true
  register: kubescape_checksum

- name: "Download kubescape"
  ansible.builtin.get_url:
    url: https://github.com/kubescape/kubescape/releases/latest/download/kubescape-ubuntu-latest
    checksum: "sha256:{{ kubescape_checksum.content }}"
    dest: /usr/local/bin/kubescape
    mode: 0755
    owner: root
    group: root
