- name: Proxmox Virtual Environment Configuration
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    # Must run before users to make sure the apt repositories are configured in order to install sudo
    - name: Configure proxmox apt repositories
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_apt
      tags: [ init, apt ]

    # Root's password must be set so that it can be used to communicate with Proxmox API
    - name: Create users
      ansible.builtin.import_role:
        name: homecentr.system.users
      tags: [ init, users ]

    - name: Configure proxmox user and their permissions
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_users
      tags: [ init, users ]

    - name: Configure https port forwarding
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_https_forward
      tags: [ pve-https-forward ]

    - name: Configure PCI passthrough dependencies
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_pci_passthrough
      tags: [ pve-pci-passthrough ]

    - name: Configure SMTP
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_smtp
      tags: [ pve-smtp ]

    - name: Configure SSO via Open ID
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_sso_openid
      tags: [ pve-sso-openid ]

    - name: Apply corosync fix
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_corosync_fix
      tags: [ corosync ]

    - name: Remove the no-subscription warning
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_nosubs_warning
      tags: [ no-subs-warning ]

    - name: Configure USB HID quirk for UPS communication
      ansible.builtin.import_role:
        name: homecentr.system.usbhid_quirk
      tags: [ usbhid-quirk ]

    - name: Configure ZFS
      ansible.builtin.import_role:
        name: homecentr.system.zfs_configuration
      tags: [ usbhid-quirk ]

    - name: Configure local storage
      ansible.builtin.import_role:
        name: homecentr.proxmox.pve_local_storage
      tags: [ vm, pve-storage ]
      vars:
        pve_local_storage_api_user: root@pam
        pve_local_storage_api_password: "{{ users_root_password }}"

    - name: Create host records for servers
      ansible.builtin.import_role:
        name: ../../roles/hosts
      vars:
        hosts_group_name: pve_nodes
      tags:
        - hosts

    - name: Install benchmarks
      ansible.builtin.import_role:
        name: homecentr.system.benchmarks
      tags:
        - benchmarks

    - name: Install lynis
      ansible.builtin.import_role:
        name: homecentr.system.lynis
      tags:
        - lynis

    - name: Harden the system according to lynis recommendations
      ansible.builtin.import_role:
        name: homecentr.system.lynis_hardening
      tags:
        - lynis

    - name: Install and configure Network UPS tools
      ansible.builtin.import_role:
        name: homecentr.system.ups
      tags:
        - ups

    - name: Set up Message-of-the-day
      ansible.builtin.import_role:
        name: homecentr.system.motd
      vars:
        motd_enable_ups_status: "true"
      tags:
        - motd

    - name: Flush handlers before starting the VMs & Containers
      ansible.builtin.meta: flush_handlers
