- name: Install Mosquitto
  ansible.builtin.apt:
    name: mosquitto
    state: present

- name: Create config directory
  register: app_mosquitto_config
  ansible.builtin.copy:
    dest: /etc/mosquitto/conf.d/custom.conf
    content: "{{ lookup('template', 'config.j2') }}"
    owner: mosquitto
    group: mosquitto
    mode: "0644"

- name: (Re)start service
  ansible.builtin.systemd_service:
    name: mosquitto
    state: "{{ 'restarted' if app_mosquitto_config.changed else 'started' }}"