# - name: debug
#   run_once: true
#   delegate_to: localhost
#   become: false
#   ansible.builtin.copy:
#     dest: /tmp/tls.cert
#     content: "{{ sealed_secrets.public_key }}"

# - name: debug
#   run_once: true
#   delegate_to: localhost
#   become: false
#   ansible.builtin.copy:
#     dest: /tmp/tls.key
#     content: "{{ sealed_secrets.private_key }}"

- name: Create encryption secret
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: "{{ fleet_kubeconfig_path }}"
    definition: "{{ lookup('template', 'key-secret.yml.j2') }}"
    state: present
    apply: true

- name: Install Sealed Secrets helm chart
  run_once: true
  kubernetes.core.helm:
    state: present
    create_namespace: true
    release_name: sealed-secrets
    release_namespace: kube-system
    chart_repo_url: https://bitnami-labs.github.io/sealed-secrets
    chart_ref: sealed-secrets
    chart_version: "{{ sealed_secrets_chart_version }}"
    kubeconfig_path: "{{ sealed_secrets_kubeconfig_path }}"
    wait: true
