- name: Download cloud images
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/var/lib/vz/images/{{ item.filename }}"
    checksum: "{{ item.checksum }}"
    owner: root
    group: root
    mode: 0644
  when: pve_vm_cloud_images is defined
  with_items: "{{ pve_vm_cloud_images }}"
