- name: Create cloud-init config
  ansible.builtin.copy:
    dest: "{{ pve_virtual_machines_local_storage.proxmox_storages[0].path }}/snippets/{{ vm.vmid }}.yml"
    owner: root
    group: root
    mode: 0640
    force: true
    content: |
      #cloud-config
      hostname: {{ vm.name }}
      manage_etc_hosts: false
      user: "{{ (users_admin_users | first).username }}"
      password: Heslo123
      chpasswd:
        expire: false
      users:
        - default
      {% for user in users_admin_users %}
        - name: {{ user.username }}
          sudo: ALL=(ALL) NOPASSWD:ALL
          ssh_authorized_keys:
      {% for key in user.public_keys %}
          - {{ key }}
      {% endfor %}
      {% endfor %}
      package_upgrade: true

- name: Create virtual machine
  community.general.proxmox_kvm:
    vmid: "{{ vm.vmid }}"
    proxmox_default_behavior: no_defaults
    node: "{{ ansible_hostname }}"
    kvm: true
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    name: "{{ vm.name }}"
    protection: "{{ vm.protection | default(true) }}"
    acpi: "{{ vm.acpi | default(true) }}"
    autostart: "{{ vm.autostart | default(true) }}"
    onboot: "{{ vm.onboot | default(true) }}"
    ostype: "{{ vm.ostype | default('l26') }}"
    boot: "{{ vm.boot_order | default('cd') }}"
    ciuser: "{{ (users_admin_users | first).username }}"
    cipassword: "Heslo123"
    sshkeys: "{{ (users_admin_users | first).public_keys | join('\n') }}"
    cicustom: "user=local:snippets/{{ vm.vmid }}.yml"
    bios: "{{ 'seabios' if (vm.bios | default('bios')) != 'efi' else 'ovmf' }}"
    startup: "down={{ vm.shutdown_timeout_seconds }}"
    # required due to a bug: https://forum.proxmox.com/threads/kernel-panic-after-resizing-a-clone.93738/
    # which causes kernel panic after resizing the os disk
    serial:
      serial0: socket
    scsi:
      scsi0: 'local-zfs:cloudinit,format=raw'
    net:
      net0: "virtio,bridge={{ vm.nic_bridge }}"
    ipconfig:
      ipconfig0: "ip={{ (vm.nic_ipv4_address + '/' + vm.nic_ipv4_subnet) | ansible.utils.ipaddr('host/prefix') }},gw={{ vm.nic_ipv4_gateway }}"  # noqa yaml[line-length]
    nameservers: "{{ vm.nameservers }}"
    efidisk0: "{{ ({'storage': vm.os_storage, 'format': 'raw', 'efitype': '4m', 'pre_enrolled_keys': false}) if (vm.bios | default('bios')) == 'efi' else none }}" # noqa yaml[line-length]
    scsihw: virtio-scsi-pci
    bootdisk: scsi1
    tablet: false
    cpu: "{{ vm.cpu_type | default('kvm64') }}"
    vcpus: "{{ vm.cpu_count * vm.cpu_cores_per_cpu }}"
    sockets: "{{ vm.cpu_count }}"
    cores: "{{ vm.cpu_cores_per_cpu }}"
    memory: "{{ vm.max_memory }}"
    balloon: "{{ vm.min_memory }}"
    state: present

- name: Import disk from cloud image
  register: vm_disk
  retries: 5 # transient timeouts
  until: vm_disk.vmid == vm.vmid
  community.general.proxmox_disk:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    disk: scsi1
    import_from: "/var/lib/vz/images/{{ vm.cloud_image_filename }}"
    storage: "{{ vm.os_storage }}"
    ssd: true
    timeout: 600
    state: present

- name: Resize imported system disk
  community.general.proxmox_disk:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    disk: scsi1
    size: "{{ vm.os_disk_size }}"
    state: resized

- name: Start VM
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    vmid: "{{ vm.vmid }}"
    node: "{{ ansible_hostname }}"
    state: started

- name: Wait for VM to start responding on SSH
  ansible.builtin.wait_for:
    host: "{{ vm.nic_ipv4_address }}"
    port: 22
    timeout: 400
    sleep: 2
    msg: "VM {{ vm.name }} did not start responding on SSH in time."
