- name: Create config directory
  ansible.builtin.file:
    path: /etc/gatus
    state: directory

- name: Create state directory
  ansible.builtin.file:
    path: /var/gatus
    state: directory

- name: Create config file
  ansible.builtin.copy:
    dest: /etc/gatus/config.yaml
    force: true
    content: "{{ lookup('template', 'config.j2') }}"

- name: Create compose file
  ansible.builtin.copy:
    dest: /etc/gatus/docker-compose.yaml
    force: true
    content: "{{ lookup('template', 'docker-compose.j2') }}"

# Gatus picks up updates in the config file by itself without the need to restart the service
- name: Start docker stack
  community.docker.docker_compose_v2:
    project_src: /etc/gatus
    state: "present"
