- name: Download MongoDB apt key
  ansible.builtin.get_url:
    url: https://dl.ui.com/unifi/unifi-repo.gpg
    dest: /usr/share/keyrings/unifi-repo.gpg

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [ signed-by=/usr/share/keyrings/unifi-repo.gpg ] https://www.ui.com/downloads/unifi/debian stable ubiquiti"
    state: present
    filename: ubnt-unifi
    update_cache: true

- name: Install Unifi Controller
  ansible.builtin.apt:
    name: unifi
    state: present
