- name: Check if ACME domain is already configured
  ansible.builtin.command:
    cmd: "grep -Fxq \"acmedomain{{ index }}: domain={{ domain }},plugin={{ pve_acme_plugin_name }}\" /etc/pve/local/config"
  register: acme_domain_list
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: Add ACME domain configuration
  ansible.builtin.command:
    cmd: pvenode config set --acmedomain{{ index }} domain={{ domain }},plugin={{ pve_acme_plugin_name }}
  when: acme_domain_list.rc != 0
  changed_when: true
  notify: Order ACME certificates
