- name: Create application container
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tags: create-container
  tasks:
    - name: Create application container
      ansible.builtin.import_role:
        name: ../../roles/app-container
      vars:
        container_inventory_name: app_coredns_primary
      # TODO: Add loop of all instances

- name: Setup Coredns containers
  hosts: app_coredns_primary # TODO: Replace with group
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tags: configure-container
  tasks:
    - name: Run common set up
      ansible.builtin.include_tasks:
        file: _common.yaml

    - name: Install coredns
      ansible.builtin.import_role:
        name: ../../roles/app-coredns
    