- name: Install required packages
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Add a host into the configuration (short name)
      become: false
      community.general.ssh_config:
        user: "{{ ansible_user }}"
        host: "{{ hostvars[item].ansible_hostname }}"
        hostname: "{{ hostvars[item].ansible_hostname }}"
        forward_agent: true # To enable YubiKey forwarding
        proxycommand: "{{ lookup('env', 'HOME') }}/.ssh/proxy.sh %h %r"
        remote_user: "{{ ansible_user }}"
        state: present
      with_items: "{{ groups['all'] }}"

    - name: Add a host into the configuration (full name)
      become: false
      community.general.ssh_config:
        user: "{{ ansible_user }}"
        host: "{{ hostvars[item].ansible_hostname }}"
        hostname: "{{ hostvars[item].fqdn }}"
        forward_agent: true # To enable YubiKey forwarding
        proxycommand: "{{ lookup('env', 'HOME') }}/.ssh/proxy.sh %h %r"
        remote_user: "{{ ansible_user }}"
        state: present
      with_items: "{{ groups['all'] }}"
