- name: Install required packages
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable CanonicalizeHostname
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0600"
        regex: "^CanonicalizeHostname .*"
        line: "CanonicalizeHostname yes"
        insertbefore: BOF

    - name: Configure CanonicalDomains
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0600"
        regex: "^CanonicalDomains .*"
        line: "CanonicalDomains {{ domain }}"
        insertbefore: BOF

    - name: Add match blocks to the ssh config
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        create: false
        marker: "# {mark} Homecentr SSH configuration"
        block: |
          Match host=pve*.{{ domain }},app-*.{{ domain }} exec "dig -t a '%h' +short | tail -n1 | grepcidr '10.0.0.0/8'"
            ForwardAgent yes

          Match host=pve*.{{ domain }},app-*.{{ domain }} exec "dig -t a '%h' +short | tail -n1 | grepcidr -v '10.0.0.0/8'"
            ForwardAgent yes
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
