- name: Install fail2ban (Debian).
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Copy fail2ban custom configuration file into place.
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Ensure fail2ban is running and enabled on boot.
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
