- name: Get host ssh key (hostname)
  ansible.builtin.command:
    cmd: "ssh-keyscan -t rsa {{ inventory_hostname }} | cut -d' ' -f 3"
  register: ssh_key
  changed_when: false

- name: Add ssh key to known_hosts (hostname)
  ansible.builtin.known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ hostvars[item].inventory_hostname }}"
    key: "{{ hostvars[item].ssh_key.stdout }}"
  with_items: "{{ groups['all'] }}"

# {{ hostvars[item].ansible_hostname }} ssh-rsa 

# - name: Get host ssh key (ipv4)
#   ansible.builtin.command:
#     cmd: "ssh-keyscan -t rsa {{ ansible_host }} | cut -d' ' -f 3"
#   register: ssh_key_ipv4
#   changed_when: false

# - name: Add ssh key to known_hosts (ipv4)
#   ansible.builtin.known_hosts:
#     path: /etc/ssh/ssh_known_hosts
#     name: "{{ hostvars[item].ansible_host }}"
#     key: "{{ hostvars[item].ansible_host }} ssh-rsa {{ hostvars[item].ssh_key_ipv4.stdout }}"
#   with_items: "{{ groups['all'] }}"
