- name: Install required pip modules
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: proxmoxer

# Download iso images to /var/lib/vz/template/iso/*.iso

# - name: Download os templates
#   ansible.builtin.command:
#     cmd: pveam download local debian-11-standard_11.3-1_amd64.tar.zst # TBA: Variable
#   register: ostemplate_download
#   changed_when: '"no need to download" in ostemplate_download.stdout'

# - name: Download Debian template
#   community.general.proxmox_template:
#     node: "{{ ansible_hostname }}" # TBD: From parameters
#     api_user: root@pam
#     api_password: "{{ users_root_password }}"
#     api_host: 127.0.0.1
#     storage: local
#     content_type: vztmpl
#     template: debian-11-standard_11.3-1_amd64.tar.zst

- name: Create new VM with minimal options
  community.general.proxmox_kvm:
    node: "{{ ansible_hostname }}" # TBD: From parameters
    api_user: root@pam
    api_password: "{{ users_root_password }}"
    api_host: 127.0.0.1
    name: test-vm
    protection: true
    ostype: l26

    args: >- # noqa yaml[line-length]
      '-kernel /media/linux -initrd /media/initrd.gz -append "preseed/url=http:10.1.1.2/ksfile.cfg locale=en_GB.UTF-8 keyboard-configuration/layoutcode=gb hostname=unassigned interface=ens3"'
    state: present


# - name: Create new VM
#   # run_once: true # Would be replaced by VM vars for the specific machine
#   community.general.proxmox:
#     proxmox_default_behavior: 'no_defaults'
#     vmid: 101
#     node: "{{ ansible_hostname }}" # TBD: From parameters
#     api_user: root@pam
#     api_password: "{{ users_root_password }}"
#     api_host: 127.0.0.1
#     hostname: "test-vm"
#     ostemplate: "local:vztmpl/debian-11-standard_11.3-1_amd64.tar.zst"
