- name: Get container config
  changed_when: false
  register: app_container_config
  ansible.builtin.command:
    cmd: "pct config {{ app_container_info.vmid }}"

- name: Add disks
  loop: "{{ container_vars.app_container_mounts | selectattr('type', 'equalto', 'disk') }}"
  loop_control:
    loop_var: disk
  when: not 'mp' + disk.index | string + ':' in app_container_config.stdout
  changed_when: true
  ansible.builtin.command:
    cmd: "pct set {{ app_container_info.vmid }} --mp{{ disk.index }} \"{{ disk.storage_name }}:{{ disk.size_gb }},mp={{ disk.target_path }}\""
