- name: Create container
  when: inventory_hostname == hostvars[container_inventory_name].app_container_pve_node
  ansible.builtin.include_tasks:
    file: container.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"

- name: Initialize container
  when: inventory_hostname == hostvars[container_inventory_name].app_container_pve_node
  ansible.builtin.include_tasks:
    file: init.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"

- name: Add container to ssh known_hosts
  when: inventory_hostname == hostvars[container_inventory_name].app_container_pve_node
  ansible.builtin.include_tasks:
    file: ssh.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"

- name: Configure replication
  ansible.builtin.include_tasks:
    file: replication.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"

- name: Configure high-availability
  ansible.builtin.include_tasks:
    file: ha.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"

- name: Configure container firewall
  when: inventory_hostname == hostvars[container_inventory_name].app_container_pve_node
  ansible.builtin.include_tasks:
    file: firewall.yaml
  vars:
    container_vars: "{{ hostvars[container_inventory_name] }}"