- name: Configure storage replication
  run_once: true
  loop: "{{ container_vars.app_container_pve_replication_nodes }}"
  loop_control:
    loop_var: node
    index_var: node_index
  ansible.builtin.blockinfile:
    path: "/etc/pve/replication.cfg"
    create: true
    owner: root
    group: www-data
    mode: "0640"
    marker: "# {mark} Ansible managed replication ct{{ app_container_info.vmid }}-{{ hostvars[node].ansible_hostname }}"
    prepend_newline: true
    block: |
      local: {{ app_container_info.vmid }}-{{ node_index }}
        source {{ hostvars[container_vars.app_container_pve_node].ansible_hostname }}
        target {{ hostvars[node].ansible_hostname }}
        schedule {{ container_vars.app_container_pve_replication_cron_expression }}
        {%- if container_vars.app_container_pve_replication_bandwidth | default("") != "" %}
        rate {{ container_vars.app_container_pve_replication_bandwidth }}
        {%- endif %}