- name: Scan for container SSH host keys
  changed_when: false
  run_once: true
  retries: 5
  until: app_container_ssh_scan.rc == 0
  register: app_container_ssh_scan
  ansible.builtin.shell:
    cmd: "pct exec {{ app_container_info.vmid }} cat /etc/ssh/ssh_host_rsa_key.pub"

- name: Update known_hosts
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.known_hosts:
    key: "{{ container_vars.ansible_host }} {{ item }}"
    name: "{{ container_vars.ansible_host }}"
  with_items: "{{ app_container_ssh_scan.stdout_lines }}"