- name: Add mapped uids to setuid
  loop: "{{ container_vars.app_container_mapped_uids | default([]) }}"
  loop_control:
    loop_var: uid
  ansible.builtin.lineinfile:
    path: /etc/subuid
    create: false
    line: "root:{{ uid }}:1"

- name: Add mapped gids to setgid
  loop: "{{ container_vars.app_container_mapped_gids | default([]) }}"
  loop_control:
    loop_var: gid
  ansible.builtin.lineinfile:
    path: /etc/subgid
    create: false
    line: "root:{{ gid }}:1"
