- name: Create application container
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create application container
      ansible.builtin.import_role:
        name: ../../roles/app-container
      vars:
        container_inventory_name: "monitoring"
      tags: [ container ]

- name: Setup Monitoring container
  hosts: monitoring
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Run common set up
      ansible.builtin.import_tasks:
        file: _common.yaml
      tags: [ common ]

    - name: Install Docker
      ansible.builtin.import_role:
        name: ../../roles/docker
      tags: [ docker ]

    - name: Install gatus
      ansible.builtin.import_role:
        name: ../../roles/app-gatus
      tags: [ gatus ]

    # TODO: Prometheus
    # TODO: Grafana
    