- name: Create application container
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create application container
      ansible.builtin.include_role:
        name: ../../roles/app-container
      vars:
        container_inventory_name: "pihole"
      tags: [ container ]

- name: Setup Pihole containers
  hosts: pihole
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Run common set up
      ansible.builtin.import_tasks:
        file: _common.yaml
      tags: [ common ]

    - name: Create pihole group
      ansible.builtin.group:
        name: pihole
      tags: [ pihole ]

    - name: Create pihole user
      ansible.builtin.user:
        name: pihole
        group: pihole
        create_home: true
      tags: [ pihole ]

    - name: Install pihole
      ansible.builtin.import_role:
        name: ../../roles/app-pihole
      tags: [ pihole ]
    