- name: Create application container
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create application container
      ansible.builtin.import_role:
        name: ../../roles/app-container
      vars:
        container_inventory_name: smtp_relay
      tags: [ container ]

- name: Setup SMTP relay container
  hosts: smtp_relay
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Run common set up
      ansible.builtin.include_tasks:
        file: _common.yaml
      tags: [ common ]

    - name: Install Docker
      ansible.builtin.import_role:
        name: ../../roles/docker
      tags: [ docker ]

    - name: Install Haraka relay
      ansible.builtin.import_role:
        name: ../../roles/app-haraka
      tags: [ haraka ]
