- name: Create application container
  hosts: pve_nodes
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create application container
      ansible.builtin.import_role:
        name: ../../roles/app-container
      vars:
        container_inventory_name: "unifi_controller"
      tags: [ container ]

- name: Setup Unifi Controller container
  hosts: unifi_controller
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Run common set up
      ansible.builtin.include_tasks:
        file: _common.yaml
      tags: [ common ]

    - name: Install Unifi Controller
      ansible.builtin.import_role:
        name: ../../roles/app-unifi-controller
      tags: [ unifi, unifi-controller ]
