- name: Download kubernetes manifests
  ansible.builtin.uri:
    url: https://github.com/fluxcd/flux2/releases/download/{{ fluxcd_version }}/install.yaml
    return_content: true
  register: fluxcd_manifests

- name: Create fluxcd resources
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: "{{ fluxcd_kubeconfig_path }}"
    definition: "{{ fluxcd_manifests.content }}"
    state: present
    apply: true
