- name: Create mount directory
  ansible.builtin.file:
    path: "{{ gluster_volume.mount_path }}"
    state: directory
    owner: root
    group: root
    mode: 0770

- name: Mount volume
  ansible.posix.mount:
    path: "{{ gluster_volume.mount_path }}"
    src: "{{ hostvars[gluster_mount_host].gluster_hostname }}:/{{ gluster_volume.name }}"
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted
