- name: "Common set up on all servers"
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create users
      ansible.builtin.import_role:
        name: homecentr.system.users
      tags:
        - users

    - name: Create host records for servers
      ansible.builtin.import_role:
        name: ../../roles/hosts
      tags:
        - hosts

    - name: Setup Chrony (NTP client)
      ansible.builtin.import_role:
        name: homecentr.system.chrony
      tags:
        - chrony
        - ntp

    - name: Install benchmarks
      ansible.builtin.import_role:
        name: homecentr.system.benchmarks
      tags:
        - benchmarks

    - name: Install lynis
      ansible.builtin.import_role:
        name: homecentr.system.lynis
      tags:
        - lynis

    - name: Harden the system according to lynis recommendations
      ansible.builtin.import_role:
        name: homecentr.system.lynis_hardening
      tags:
        - lynis

    - name: Install ClamAV antivirus
      ansible.builtin.import_role:
        name: homecentr.system.clamav
      tags:
        - clamav

    - name: Configure and secure SSH
      ansible.builtin.import_role:
        name: homecentr.system.ssh
      tags:
        - ssh

    - name: Install and configure Network UPS tools
      ansible.builtin.import_role:
        name: homecentr.system.ups
      tags:
        - ups

    - name: Install zfs-auto-snapshot
      ansible.builtin.apt:
        name: zfs-auto-snapshot
      tags:
        - zfs-auto-snapshot

    - name: Set up Message-of-the-day
      ansible.builtin.import_role:
        name: homecentr.system.motd
      vars:
        motd_enable_ups_status: "true"
      tags:
        - motd

    - name: Install node-exporter
      ansible.builtin.import_role:
        name: geerlingguy.node_exporter
      tags:
        - node_exporter
        - node-exporter
