- name: Set up gluster cluster
  hosts: gluster_servers
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
  - import_role:
      name: ../roles/gluster/server

- name: Set up gluster clients
  hosts: gluster_clients
  become: true
  become_method: sudo
  tasks:
  - import_role:
      name: ../roles/gluster/client