- name: Set up Kubernetes cluster
  hosts: k8s_nodes
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
  - name: Install and configure k3s
    ansible.builtin.import_role:
      name: ../roles/kubernetes/k3s-cluster
    tags:
      - k3s

  # - name: Install and configure Local Storage
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/local-storage
  #   tags:
  #     - local-storage

  # - name: Install and configure Metal Load Balancer
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/metal-lb
  #   tags:
  #     - metallb

  # - name: Install and configure Traefik ingress
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/ingress
  #   tags:
  #     - ingress

  # - name: Install and configure Cert Manager
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/cert-manager
  #   tags:
  #     - cert-manager

  # - name: Install and configure Reflector
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/reflector
  #   tags:
  #     - reflector

  # - name: Install and configure Prometheus operator
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/prometheus-operator
  #   tags:
  #     - prometheus-operator
  #     - prometheus

  - name: Install and configure Sealed secrets
    ansible.builtin.import_role:
      name: ../roles/kubernetes/sealed-secrets
    tags:
      - sealed-secrets

  # - name: Install and configure fleet
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/fleet
  #   tags:
  #     - fleet

  - name: Install and configure argo cd
    ansible.builtin.import_role:
      name: ../roles/kubernetes/argocd
    tags:
      - argocd
