- name: Set up Kubernetes cluster
  hosts: k8s_nodes
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
  - name: Install and configure k3s
    ansible.builtin.import_role:
      name: ../roles/kubernetes/k3s-cluster
    tags:
      - k3s

  - name: Install and configure Argo CD
    ansible.builtin.import_role:
      name: ../roles/kubernetes/argo-cd
    tags:
      - argocd
