- name: Set up Kubernetes cluster
  hosts: k8s_cluster
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Install Kubernetes cluster (RKE 2)
      ansible.builtin.import_role:
        name: lablabs.rke2
      tags:
        - k8s
        - rke2

    - name: Configure sysctls
      ansible.builtin.import_role:
        name: ../../roles/k8s-sysctls
      tags:
        - k8s
        - rke2

    - name: Install python modules for k8s management
      ansible.builtin.import_role:
        name: ../../roles/k8s-python-modules
      tags:
        - always

    - name: Install helm
      ansible.builtin.import_role:
        name: geerlingguy.helm
      tags:
        - helm

    - name: Install Longhorn dependencies
      ansible.builtin.import_role:
        name: ../../roles/k8s-longhorn-dependencies
      tags:
        - longhorn-deps

    # - name: Install and configure Argo CD
    #   ansible.builtin.import_role:
    #     name: ../../roles/k8s-argocd
    #   tags:
    #     - argocd
