- name: Set up Kubernetes cluster
  hosts: k8s_nodes
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
  - name: Install and configure k3s
    ansible.builtin.import_role:
      name: ../roles/kubernetes/k3s-cluster
    tags:
      - k3s

  - name: Install and configure fleet
    ansible.builtin.import_role:
      name: ../roles/kubernetes/fleet
    tags:
      - fleet

  - name: Install and configure Sealed secrets
    ansible.builtin.import_role:
      name: ../roles/kubernetes/sealed-secrets
    tags:
      - sealed-secrets

  # - name: Install and configure fluxcd
  #   ansible.builtin.import_role:
  #     name: ../roles/kubernetes/fluxcd
  #   tags:
  #     - fluxcd

  # GitRepository - add name from a variable
  #               - add namespace which should be defaulted to flux-system

  # TBA: install and configure the secret provider