- name: Set up Kubernetes cluster
  hosts: k8s_cluster
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Create ZFS datasets for rke2
      ansible.builtin.import_role:
        name: ../../roles/k8s-cluster-prerequisites
      tags:
        - prereqs

    - name: Install Longhorn dependencies
      ansible.builtin.import_role:
        name: ../../roles/k8s-longhorn-dependencies
      tags:
        - longhorn-deps

    - name: Install helm
      ansible.builtin.import_role:
        name: geerlingguy.helm
      tags:
        - helm

    - name: Install rke2 cluster
      ansible.builtin.import_role:
        name: lablabs.rke2
      tags:
        - rke2

    # - name: Install and configure Argo CD
    #   ansible.builtin.import_role:
    #     name: ../../roles/k8s-argocd
    #   tags:
    #     - argocd
