- name: Set up Kubernetes cluster
  hosts: k8s_cluster
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Install helm
      ansible.builtin.import_role:
        name: geerlingguy.helm
      tags:
        - helm

    - name: Set up storage
      ansible.builtin.import_role:
        name: ../../roles/k8s-storage
      tags:
        - storage
      when: k8s_storage_enabled == true

    - name: Install and configure the rke2 cluster
      ansible.builtin.import_role:
        name: ../../roles/k8s-cluster
      tags:
        - cluster

    - name: Install and configure Argo CD
      ansible.builtin.import_role:
        name: ../../roles/k8s-argocd
      tags:
        - argocd
