- name: Install python modules
  hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.pip:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - netaddr
          - stormssh
    