- name: Proxmox Virtual Environment Configuration
  hosts: pve_nodes
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
    # Root's password must be set so that it can be used to communicate with Proxmox API
    - name: Create users
      ansible.builtin.import_role:
        name: ../roles/common/users
      tags:
        - users

    - name: Configure Proxmox VE specific components
      ansible.builtin.import_role:
        name: ../roles/proxmox/pve-node
      tags:
        - pve-nodes

    - name: Create virtual machines
      ansible.builtin.import_role:
        name: ../roles/proxmox/virtual-machines
      tags:
        - vm
