rke2_type: server # All nodes are servers

rke2_ha_mode: true
rke2_ha_mode_kubevip: true
rke2_ha_mode_keepalived: false
rke2_kubevip_cloud_provider_enable: true
rke2_kubevip_svc_enable: true
rke2_kubevip_image: ghcr.io/kube-vip/kube-vip:v0.6.4
rke2_kubevip_cloud_provider_image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.4

rke2_api_ip: 10.1.8.200 # TBA: Assign a different IP
rke2_api_cidr: 24

rke2_version: v1.28.4+rke2r1
rke2_drain_node_during_upgrade: true

rke2_disable:
  - rke2-ingress-nginx
  - rke2-metrics-server

rke2_server_options:
  - "cluster-cidr: 172.16.0.0/16" # Pod internal IP addresses
  - "service-cidr: 172.17.0.0/16" # Services internal IP addresses

# TODO: etcd snapshot backup to S3 ?