app_homepage_settings:
  title: "Homecentr{{ env.suffix_display }}"
  favicon: /icons/favicon.ico
  background: https://images.unsplash.com/photo-1519681393784-d120267933ba
  backgroundOpacity: 0.3
  theme: dark
  color: neutral
  headerStyle: clean