app_pomerium_hostname: login-lab.homecentr.one

app_pomerium_groups_administrators: b77c210d-8ae3-4292-9e95-c7d42a2f254f
app_pomerium_groups_users: ba84af15-129a-42c3-806c-62700ea31a7c

app_pomerium_certificates:
  - fullchain_path: /getssl/wildcard_fullchain.crt
    key_path: /getssl/wildcard.key

app_pomerium_routes:
  - from: https://pihole-lab.homecentr.one
    to: http://10.1.8.128
    auth_mode: administrators
  # - from: https://gatus-lab.homecentr.one
  #   to: http://10.1.8.128
  #   auth_mode: administrators