name: Release
on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Write ssh key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ${{ runner.temp }}/ssh.key
          chmod 0600 ${{ runner.temp }}/ssh.key

      - name: Run Ansible playbooks
        run: yarn prod:apply _all -e ansible_user=github-runner --private-key ${{ runner.temp }}/ssh.key
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: "false"

  e2e-prod-local:
    uses: homecentr/e2e/.github/workflows/run-e2e.yml
    needs:
      - deploy-lab
    with:
      environment: prod
      client: local
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}

  e2e-prod-remote:
    uses: homecentr/e2e/.github/workflows/run-e2e.yml
    needs:
      - deploy-prod
    with:
      environment: prod
      client: remote
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}