name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To add version tags
      issues: write   # Semantic release to link issues
    steps:
      - uses: actions/checkout@master

      - name: Create GitHub release
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
