name: CI
on:
  pull_request:

jobs: 
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pre-requisites
        run: |
          yarn
          sudo wget -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          sudo chmod a+x /usr/bin/sops
          python3 -m pip install --force-reinstall ansible==7.6.0
          python3 -m pip install --force-reinstall ansible-lint==6.16.2

      - name: Lint Ansible files
        run: yarn lint

      - name: Compare values across environments
        run: yarn validate-values

  # TODO: Deploy lab from self-hosted
  # TODO: Run E2E tests from self-hosted (remote + local)