name: CI
on:
  pull_request:

jobs: 
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pre-requisites
        run: |
          sudo wget -q -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          yarn
          sudo chmod a+x /usr/bin/sops
          sudo pip install --upgrade pip
          sudo pip uninstall -y ansible-core
          pip install --force-reinstall ansible==7.6.0
          pip install --force-reinstall ansible-lint==6.17.0

      - name: Lint Ansible files
        run: yarn lint

      - name: Compare values across environments
        run: yarn validate-values
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
