name: CI
on:
  pull_request:

jobs: 
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pre-requisites
        run: |
          yarn
          sudo wget -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          sudo chmod a+x /usr/bin/sops
          sudo pip install --force-reinstall ansible==7.6.0
          sudo pip install --force-reinstall ansible-lint==6.17.0

      - name: Debug
        run: |
          ansible-playbook --version

      - name: Lint Ansible files
        run: yarn lint

      - name: Compare values across environments
        run: yarn validate-values

  deploy-lab:
    runs-on: self-hosted
    needs:
      - validate
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Ansible playbooks
        run: yarn lab:apply

  # Run in parallel
  # TBA: e2e-lab-local:
  # TBA: e2e-lab-remote: