# Note: this role is not using the existing gluster.gluster modules because the module for managing volumes is poorly designed
# (doesn't for example support allow specifying individual brick paths). Another reason is that this way ansible creates the volume(s)
# if they don't exist but doesn't touch them if they already do. This isn't ideal but it's safer because it can never corrupt a volume containing data.

- name: Validate storage bricks count
  run_once: true
  ansible.builtin.assert:
    quiet: true
    that:
      - gluster_validation_item.0.storage_bricks | count == gluster_validation_item.1
    msg: |-
      Storage bricks for volume {{ gluster_volume_config.name }} do not match.
      Found {{ gluster_validation_item.0.storage_bricks | count }} bricks, expected {{ gluster_validation_item.1 }}
  loop: "{{ gluster_volume_config.replica_sets | product([gluster_volume_config.replicas]) }}"
  loop_control:
    loop_var: gluster_validation_item

- name: Validate arbiter bricks count
  run_once: true
  ansible.builtin.assert:
    quiet: true
    that:
      - gluster_validation_item.0.arbiter_bricks | count == gluster_validation_item.1
    msg: |-
      Arbiter bricks for volume {{ gluster_volume_config.name }} do not match.
      Found {{ gluster_validation_item.0.arbiter_bricks | count }} bricks, expected {{ gluster_validation_item.1 }}
  loop: "{{ gluster_volume_config.replica_sets | product([gluster_volume_config.arbiters]) }}"
  loop_control:
    loop_var: gluster_validation_item

- name: Check if volume exists
  ansible.builtin.command:
    cmd: "gluster volume info {{ gluster_volume_config.name }}"
  failed_when: false
  changed_when: false
  register: volume_exists

- name: Create storage bricks directories if they do not exist
  ansible.builtin.file:
    path: "{{ brick.path }}"
    state: directory
    owner: root
    group: root
    mode: 0770
  loop: "{{ gluster_volume_config.replica_sets | map(attribute='storage_bricks') | flatten | selectattr('host', 'equalto', inventory_hostname) }}"
  loop_control:
    loop_var: brick
  when: volume_exists.rc != 0

- name: Create arbiter bricks directories if they do not exist
  ansible.builtin.file:
    path: "{{ brick.path }}"
    state: directory
    owner: root
    group: root
    mode: 0770
  loop: "{{ gluster_volume_config.replica_sets | map(attribute='arbiter_bricks') | flatten | selectattr('host', 'equalto', inventory_hostname) }}"
  loop_control:
    loop_var: brick
  when: volume_exists.rc != 0

- name: Create volume if does not exist
  run_once: true
  ansible.builtin.command:
    cmd: "{{ lookup('template', 'create-volume-command.j2') }}"
  changed_when: volume_exists.rc != 0
  when: volume_exists.rc != 0

- name: Enable server tls
  run_once: true
  ansible.builtin.command:
    cmd: "gluster volume set {{ gluster_volume_config.name }} server.ssl on"
  changed_when: true

- name: Enable client tls
  run_once: true
  ansible.builtin.command:
    cmd: "gluster volume set {{ gluster_volume_config.name }} client.ssl on"
  changed_when: true

- name: Set allowed clients
  run_once: true
  ansible.builtin.command:
    cmd: "{{ lookup('template', 'set-volume-clients-command.j2') }}"
  changed_when: true

- name: Apply option groups
  run_once: true
  changed_when: true
  ansible.builtin.command:
    cmd: "gluster volume set {{ gluster_volume_config.name }} group {{ group_name }}"
  loop: "{{ gluster_volume_config.option_groups }}"
  loop_control:
    loop_var: group_name
  when: "'option_groups' in gluster_volume_config"

- name: Check volume status
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gluster volume info {{ gluster_volume_config.name }} | grep 'Status:' | cut -d' ' -f2
  args:
    executable: /bin/bash
  changed_when: false
  register: volume_status

- name: Start the volume
  run_once: true
  ansible.builtin.command:
    cmd: "gluster volume start {{ gluster_volume_config.name }}"
  changed_when: volume_status.stdout != "Started"
  when: volume_status.stdout != "Started"

- name: Configure quota
  run_once: true
  ansible.builtin.include_tasks:
    file: create-volume-quota.yml