- name: Install Gluster server
  register: gluster_server_install
  ansible.builtin.apt:
    name: glusterfs-server
    state: present
    update_cache: true

- name: Start the Gluster daemon
  register: gluster_server_daemon_start
  until: gluster_server_daemon_start.status.ActiveState == "active"
  delay: 20
  retries: 15
  throttle: 1
  ansible.builtin.service:
    name: glusterd
    state: started
    enabled: true
